bcgov/zeva

backend/api/fixtures/operational/0005_add_plugin_hybrid_vehicles.py, backend/api/fixtures/operational/0006_add_battery_electric_vehicles.py, backend/requirements.txt, frontend/src/app/config.js, frontend/webpack.config.js, k8s-frontend.yaml
- Frontend now loads `KEYCLOAK_CLIENT_ID` and `KEYCLOAK_REALM_NAME` environment vars
- Backend fixtures adjusted to account for model changes
- `requirements.txt` updated with missing `python-dotenv` requirement
=> parameterize keycloak realm and client, backend fixes

.gitignore, backend/.coveragerc, backend/api/management/dataloader.py, backend/api/tests/test_load_ops_data.py, backend/requirements.txt
- Add `coverage` python dependency to execute tests with coverage
- Provide a sensible `.coveragerc` as a starting point
- Include operational data scripts in testing, since a lot of the issues I've seen thus far locally have been with these scripts and their maintenance will be important.
- Test coverage to 80%.
Execute tests with `coverage run` and see results with `coverage report`. `coverage report` will exit with nonzero status if coverage does not meet threshold of 80%. Recommend incorporating this command into the pipeline. The test pod must have a valid <strong>POSTGRES</strong> test database to run the tests.
=> increase test coverage

frontend/package.json, frontend/serve.js
- Create a script to serve the app via `express` rather than `webpack-dev-server`
- Disabled `eslint src` as `prepare` phase npm script. It blocks `npm install` from executing properly.
<strong>Devops notes</strong>:
- Run `npm run dist` after `npm install` in build phase to generate script and resources
- Use `node serve` as application entry point to launch service (launches on both port 5001 and 5002, as before).
- Resolves `sockjs` connection issues, and builds in production mode
=> Prebuild JS for Openshift

backend/api/management/commands/load_ops_data.py
- Operational data load script can now accept a directory parameter, and will execute scripts that follow the convention `<number>_name.py`
Call like `python3 manage.py load_ops_data --directory <path>`
Returns nonzero if any scripts report errors, 0 on success
=> Update operational data load script to permit directory arguments

frontend/src/organizations/VehicleSupplierEditContainer.js
Changelog:
- Fixed a bug where editing address line 2 undid the changes for address line 1 and vice versa.
(Since we're already populating AddressLine_1 and AddressLine_2 when we load the organization, we no longer need to maintain the values when we do HandleInputChange)
=> Bugfix: Organization Edit Address

backend/requirements.txt
Changelog:
- python-magic-bin is causing issues in openshift, so I'm just removing them as we're not using it directly
=> Removed python-magic-bin

frontend/src/vehicles/components/VehicleListTable.js
Changelog:
- Vehicle Table now uses short name by default (unless its null)
- Changed sort by for IDIR users to sort by Supplier name
=> ZEVA-252: Changed sort by when logged in as IDIR

frontend/src/vehicles/VehicleDetailsContainer.js, frontend/src/vehicles/VehicleListContainer.js, frontend/src/vehicles/components/VehicleDetailsPage.js, frontend/src/vehicles/components/VehicleListTable.js
added filtering when back button is clicked
"When you are in select ZEV model manufacturers, and then click on row to see details. You are brought to the details page which is nice. But then if you click 'baclk' to go back to your filtered search, you are instead brought back to the original list of all zev models. so you have to redefine your search criteria. Would be nice if when you select 'back' the zev model filter you applied sticks when you're switching from detailed view to filtered zev model view."
=> bug 3 back button filtering

frontend/src/credits/components/CreditRequestDetailsPage.js
after a sale has been validated, the validate button will reappear on the page with a comment box and "recommend issuance" button--swapped order of these buttons and made the recommend issuance primary, changed button to "re-validate"
=> bug 21 - Validate / revalidate / recommend issuance buttons

frontend/src/app/components/Alert.js, frontend/src/credits/components/CreditRequestDetailsPage.js, frontend/src/dashboard/components/ActionsBceid.js, frontend/src/dashboard/components/Administration.js, frontend/src/stories/DashboardPage.stories.js, frontend/src/vehicles/components/VehicleForm.js
replaced text -government- with  Government of B.C.
=> ZEVA 310 - government wording

backend/api/serializers/credit_transfer.py, frontend/src/app/css/Form.scss, frontend/src/app/router.js, frontend/src/app/routes/CreditTransfers.js, frontend/src/credits/CreditTransfersEditContainer.js, frontend/src/credits/components/CreditTransfersForm.js, frontend/src/credits/components/CreditTransfersListTable.js
-added edit ability by loading new form with prefilled values when draft record is clicked
-added serializer for updating transfer content and partner
-changed transfer container and page to be editContainer and form to match other components
-added check for partner and filled rows before saving
=> ZEVA 318 - edit credit transfer draft

backend/api/models/sales_submission_content.py, backend/api/services/sales_spreadsheet.py, frontend/src/app/constants/errorCodes.js, frontend/src/app/css/ReactTable.scss, frontend/src/credits/components/CreditRequestVINListPage.js, frontend/src/credits/components/VINListTable.js
Changelog:
- Make is now being validated when an analyst reviews a credit application
- Warning background only highlights either model year or make when receiving a 41 warning
- Added warning background on the VIN if there's no matching icbc match
- Added warning background on sales date if the format is invalid
=> ZEVA-311: Make Validation for IDIR Users

frontend/src/app/router.js, frontend/src/dashboard/DashboardContainer.js, frontend/src/dashboard/components/ActionsBceid.js, frontend/src/dashboard/components/ActionsIdir.js
Changelog:
- Dashboard alerts should no longer show credit transfers, unless enabled
- Routes to Credit transfers should now be disabled, unless enabled in the config
=> ZEVA-341: Credit Transfers should not show up if it's not enabled

backend/api/services/credit_transaction.py, frontend/src/credits/components/CreditTransactions.js
Changelog:
- Fixed ordering of items for the Credit Transactions
- Automatically create a kink between credit transfer and credit transaction when a transfer is recorded
=> ZEVA-373: Fixed Credit Transaction showing incorrect order

backend/api/viewsets/credit_transfer.py, frontend/src/app/components/Button.js, frontend/src/credits/CreditTransfersEditContainer.js, frontend/src/credits/components/CreditRequestDetailsPage.js, frontend/src/credits/components/CreditTransactionListTable.js, frontend/src/credits/components/CreditTransfersDetailsPage.js, frontend/src/credits/components/CreditTransfersDetailsTable.js, frontend/src/credits/components/CreditTransfersForm.js, frontend/src/credits/components/CreditTransfersListTable.js
1. When a BCeID user creates a transfer notice with multiple lines it is possible to skip over (not interact with) the $ value field and still submit. In this case the submit button is enables and the save button is disabled when it should be the other way round.
2. moved to Jira-404
3. IDIR user should not be able to see transfer notices that are rejected or rescinded before they are submitted to government
4. IDIR user briefly sees the BCeID transfer notice form page when they  click to view a rescinded transfer. Please change so they don't see that form.
5. When the IDIR Director is viewing a transfer notices the new balance of Tesla (the seller) appeared with many decimal places. Please change to limit the balance to 2 decimal places. 
6. The Director is receiving the 'Insufficient …
=> Thursday Jan 8 Transfer bugs and changes

backend/api/serializers/sales_submission.py, frontend/src/credits/components/CreditRequestDetailsPage.js
Changelog:
- Changed how icbc is current to is populated
- New serializer field for icbc current to which looks at the timestamp on when the checked status was created and look for an upload date closest to that without going over
=> ZEVA-420: Fixed icbc current to always showing latest date

frontend/src/credits/components/CreditTransfersDetailsPage.js
Changelog:
- Moved the signing block outside the conditional variables
=> ZEVA-431: Removed the restrictions for displaying the signing confirmations

backend/api/serializers/sales_submission.py, frontend/src/credits/components/ModelListTable.js
Changelog:
- Added conditions to check whether the user is government or if the validation status is VALIDATED
- Added backend fix to not give any hints on how many are eligible
=> ZEVA-427: Automatically hide the Eligible Columns until Validated (for BCEID)

backend/api/services/credit_transaction.py, frontend/src/credits/components/CreditTransactions.js
Changelog:
- Moved the credit transactions creation outside the initial loop when we're building the credits to be added
- Moved the account balance update outside that loop as well
- Fixed an issue where transactions are not being merged together properly
=> ZEVA-439: Fixed duplicate transactions being created

frontend/src/credits/components/CreditTransfersListTable.js, frontend/src/dashboard/components/ActionsBceid.js, frontend/src/dashboard/components/ActionsIdir.js
-Change status from "approved by transfer partner" to "submitted to government" when transfer partner approves the transfer for both bceid and idir users.
-Also, changed dashboard alert filter to new status.
=> ZEVA-442: Credit Transfer status change

frontend/src/app/components/ComplianceTabs.js, frontend/src/app/components/Navbar.js, frontend/src/app/config.js, frontend/src/app/config/features.js
Changelog:
- Re-added model year report (this is whether to show the tab 'not navigation')
- Compliance Ratio is not configurable
- Compliance Calculator is not configurable
=> ZEVA-462: Compliance Raio and Compliance Calculator to be configurable

frontend/src/app/components/Navbar.js
I didn't realize we still have that old code for the model year report
=> Removed the old model year report navigation bar

backend/api/fixtures/operational/0022_update_signing_authority_assertions.py, backend/api/serializers/model_year_report.py, backend/api/serializers/signing_authority_assertion.py, backend/api/viewsets/model_year_report_vehicle.py, backend/api/viewsets/signing_authority_assertion.py, frontend/src/compliance/ConsumerSalesContainer.js, frontend/src/compliance/CreditActivityContainer.js, frontend/src/compliance/SupplierInformationContainer.js, frontend/src/compliance/components/ComplianceReportSignOff.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js, frontend/src/compliance/components/CreditActivityDetailsPage.js, frontend/src/compliance/components/SupplierInformationDetailsPage.js, frontend/src/credits/CreditTransfersDetailsContainer.js, frontend/src/credits/CreditTransfersEditContainer.js
- added fixture to update assertion table with compliance report checkboxes.
- Updated SigningAuthorityAssertionViewSet, removed module="credit_transfer" filter and added filtering on the front end logic.
- Getting all checkboxes from the DB table and displaying them on different pages based on module value.
-  Saving checkbox confirmation values for supplier_information and consumer_sales pages.
(need to move checkbox logic from credit activity to new compliance obligation)
=> ZEVA-476:Model Year Compliance Report - Confirmations

frontend/src/app/css/ComplianceReport.scss, frontend/src/compliance/ConsumerSalesContainer.js, frontend/src/compliance/SupplierInformationContainer.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js, frontend/src/compliance/components/SupplierInformationDetailsPage.js
-Added input boxes for previous year sale instead of labels.
-saving input values to the DB.
-calculating average of 3 previous year values and supplier class based on the average.
=> ZEVA-461,477:Model Year Report - Supplier Info and Consumer Sales page changes

backend/api/serializers/model_year_report_previous_sales.py, backend/api/serializers/model_year_report_vehicle.py, backend/api/urls.py, backend/api/viewsets/model_year_report_consumer_sales.py, frontend/src/app/css/ComplianceReport.scss, frontend/src/app/routes/Compliance.js, frontend/src/compliance/ConsumerSalesContainer.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js
* Based on the report id, load the snapshots of previous_sales, vehicle_list, ldv_sales and confirmation if it exist in the DB, 
else load vehicle_list from vehicle_sales, and display input boxes for previous sales & ldv_sales. 
* Made some minor name changes and formatting
=>  ZEVA-498:Consumer Sales page - Retrieve values from the saved snapshot

backend/api/models/sales_submission_content.py
Changelog:
- Instead of checking if the date is convertible to float, we just directly parse it if the sales date is expected to be a string
=> ZEVA-539: Fixed an issue with the sales date parsing if it was stored as a string

backend/api/serializers/model_year_report_compliance_obligation.py, backend/api/viewsets/model_year_report_compliance_obligation.py, frontend/src/app/css/App.scss, frontend/src/app/routes/Compliance.js, frontend/src/compliance/ComplianceObligationContainer.js, frontend/src/compliance/ComplianceReportSummaryContainer.js, frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js, frontend/src/compliance/components/SummaryCreditActivityTable.js, frontend/src/compliance/components/SummarySupplierInfo.js
-changes obligation serializer to use id instead of year (also updates frontend)
-adds axios calls to summary container for report, supplier, consumer sales, and obligation detsails
-reworks how summary tables receive data (format has changed since frontend was originally developed)
=> ZEVA 502- retrieve values for summary page

backend/api/viewsets/vehicle.py, frontend/src/app/routes/Vehicles.js, frontend/src/compliance/ComplianceReportSummaryContainer.js, frontend/src/compliance/ConsumerSalesContainer.js
-Updated the vehicle_sales api to filter the sale submission record based on date
-made changes to summary page, get vehicleList from consumerSales snapshot.
=> ZEVA-553: Implement the time period logic (October to September) for the consumer sales vehicles

frontend/src/app/router.js, frontend/src/compliance/ComplianceReportSummaryContainer.js, frontend/src/compliance/components/ComplianceObligationDetailsPage.js, frontend/src/compliance/components/ComplianceObligationReductionOffsetTable.js, frontend/src/compliance/components/ComplianceReportAlert.js, frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js, frontend/src/compliance/components/SupplierInformationDetailsPage.js
Allow the analyst/engineer to select a report from the report list page
Load/enable view of the snapshot of the submitted report (4 pages)
The pages should be read only, and are therefore a record of the information submitted by the supplier
-disables any inputs or radio buttons if user is gov
-removes save buttons for gov users as well
=> Zeva541 - idir snapshot of model year report

backend/api/viewsets/model_year_report.py, frontend/src/app/routes/Compliance.js, frontend/src/compliance/ComplianceReportSummaryContainer.js, frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js, frontend/src/compliance/components/SupplierInformationDetailsPage.js
- Make everything read-only when status is confirmed or submitted.
- created new method for retrieving the summary confirmation.
- fixed a bug with saving summary confirmation.
=> ZEVA-571:Fix read-only logic when a page is confirmed, also fixed some issues with confirmation retrieval on summary page.

backend/api/viewsets/model_year_report_compliance_obligation.py, backend/api/viewsets/vehicle.py, frontend/src/compliance/ComplianceObligationContainer.js, frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js, frontend/src/compliance/components/SummaryCreditActivityTable.js
- Change effective date logic for model year report 
- updated vehicle sales dates for consumer sales page
- updated compliance obligation backend logic dates
- Also, minor text changes
- found a bug in offset calculation, added a fix.
=> ZEVA-570:Change the logic for the effective dates for the the model year report

backend/api/fixtures/operational/0030_update_signing_authority_assertions.py, backend/api/services/model_year_report.py, backend/api/services/vehicle.py, backend/api/viewsets/model_year_report_compliance_obligation.py, backend/api/viewsets/model_year_report_consumer_sales.py, backend/api/viewsets/vehicle.py, frontend/src/compliance/ConsumerSalesContainer.js, frontend/src/compliance/components/ComplianceReportTabs.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js, frontend/src/compliance/components/ConsumerSalesLDVModelTable.js
- Removed code related to ldv_sales and previous_sales from consumer sales pages(frontend and backend)
- Made some logic changes and moved code to the backend, (if confirmed, load data from snapshot else from DB)
- created a fixture to update consumer_sales assertion text
=> ZEVA-575:BCeID MY Report Update - Consumer (ZEV) Sales Page

frontend/src/compliance/ComplianceReportsContainer.js
-limits suppliers to which reports can be created
- if suppliers have unassessed reports, they cannot create any new ones
- if suppliers have no reports, they can create a report based on the last year of sales they have 
- OR if they have no sales they can create a report for current year or previous year
=> ZEVA 614 - prevent suppliers from skipping reports

frontend/src/app/components/CommentInput.js, frontend/src/compliance/ComplianceObligationContainer.js, frontend/src/compliance/components/AssessmentDetailsPage.js, frontend/src/compliance/components/ComplianceObligationDetailsPage.js, frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js, frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js
-makes  comment to supplier  read only  when  assessed and removes button
-fixes variables in assesssment details for  director assessment
-removes provisional wording  when  no pending records exist, now it will just say 'balance' without the provisional part in that case
-remove  submit button from summary if report has been assessed
=> monday bugs

backend/api/serializers/credit_agreement.py, backend/api/viewsets/credit_agreement.py, frontend/src/creditagreements/CreditAgreementsEditContainer.js, frontend/src/creditagreements/components/CreditAgreementsForm.js
- adds update function in save serializer for adding attachment
-starts adding some other base serializers such as get update user
-removes history.push after agreement attachment upload and instead console logs (details page not built)
-document is uploaded when agreement is submitted NOT when upload button is clicked
=> ZEVA 600 - Credit agreement feature - document upload

backend/api/serializers/dashboard.py, backend/api/urls.py, backend/api/viewsets/dashboard.py, frontend/src/app/routes/Dashboard.js, frontend/src/compliance/ComplianceReportsContainer.js, frontend/src/compliance/components/ComplianceReportListPage.js, frontend/src/compliance/components/ComplianceReportsTable.js, frontend/src/dashboard/DashboardContainer.js, frontend/src/dashboard/components/ActionsBceid.js, frontend/src/dashboard/components/ActionsIdir.js
-adds url, viewset and serializer for retrieving dashboard data
-adds model year report to new serializer
-adds model year report activities to dashboard frontend
-adds filtering ability to model year report container (so the list can be filtered when activity banner is clicked)
=> Zeva487 - add model year report to dashboard

frontend/src/app/utilities/calculateCreditReduction.js, frontend/src/compliance/ComplianceObligationContainer.js, frontend/src/compliance/components/ComplianceObligationReductionOffsetTable.js, frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
**7.** Added blank line after Credit A Reduction heading if there is no reduction data present
**8.** Inconsistency in the behavior for what happens when the user changes LDV sales number. Sometimes the A credit reduction changes without saving and other times the user has to save first - **removed the condition to calculate reduction only if credit reduction selection is there inside onchangeLdvSales function. Now user can see reduction numbers changing without saving ldvSales first**
**9.** The text for all types of balances is all caps
**10.** The unspecified credit reduction appears to default to B without the user selecting either radio button. As a result the user can currently progress to finalize the report without selecting A or B.- **added condition, radioId should be present …
=> BugFix - 7,8,9,10

backend/api/serializers/model_year_report_supplemental.py, backend/api/viewsets/model_year_report.py, frontend/src/supplementary/SupplementaryContainer.js, frontend/src/supplementary/components/SupplementaryDetailsPage.js
- fixed curly braces showing up instead of the intended value in the penalty descriptions
- Save button is visible now  when reassessment is in draft
- save button is visible to director when status is recommended so that they can edit/save the supplier comment
- Assessment descriptions are showing up now after it's been recommended
- (Fixed) Clicking on save on a Recommended Supplementary tries to redirect to an undefined report
=> ZEVA-702:Bug: Save Button and Curly Braces showing up in the Details screen (supplmentary reports)

backend/api/viewsets/model_year_report.py, frontend/src/compliance/ConsumerSalesContainer.js, frontend/src/compliance/components/ComplianceCalculatorDetailsInputs.js, frontend/src/compliance/components/ComplianceObligationDetailsPage.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js, frontend/src/users/components/UserDetailsForm.js
- order model year report list in desc order in the backend
- On consumer sales page, disable save button if there are no sales record and when confirmation checkbox is not checked.
- added a tooltip text to enter LDV sales total on compliance obligation before clicking confirmation checkbox
- update text supplier size to supplier class on calculator page
- change label from bceid User Name to User Id on admin page.
=> ZEVA-696:General bugs/enhancements & changes

backend/api/serializers/sales_submission.py, backend/api/services/vehicle.py, backend/api/viewsets/model_year_report_compliance_obligation.py, backend/api/viewsets/model_year_report_consumer_sales.py, frontend/src/compliance/AssessmentContainer.js, frontend/src/compliance/ComplianceObligationContainer.js, frontend/src/compliance/components/AssessmentDetailsPage.js, frontend/src/compliance/components/ComplianceObligationDetailsPage.js
Changelog:
- Compliance Obligation LDV Sales now start off with a blank text and will prevent submission
- Assessment Pending sales should now go away when they're processed and recommended
- Removed duplicate radio text in Assessment
- Fixed an issue with some models not showing up in consumer sales
- Fixed an issue where internal comments are showing up for bceid users
=> PROD Fixes

backend/api/serializers/model_year_report.py, backend/api/viewsets/model_year_report.py, frontend/src/app/components/Comment.js, frontend/src/app/components/CommentInput.js, frontend/src/app/components/DisplayComment.js, frontend/src/compliance/components/ComplianceReportsTable.js, frontend/src/dashboard/DashboardContainer.js, frontend/src/supplementary/SupplementaryContainer.js, frontend/src/supplementary/components/CreditActivity.js, frontend/src/supplementary/components/SupplementaryDetailsPage.js, frontend/src/supplementary/components/ZevSales.js
Changelog:
- Automatically redirect to the Supplementary/Reassessment page if applicable
- Fixed highlighting for the zev sales input
- Fixed issue with the add comment saving for the wrong supplementary report
- Fixed missing highlighting on changes
=> Fixed supplementary bugs

frontend/src/compliance/components/ComplianceHistory.js
-changes wording on history title and bullet for both supplemental and model year reports
Supplemental:
Model year report:
=> zeva 169 - change wording on model year report history accordian

backend/api/serializers/dashboard.py
Returns recommended status model year reports as 'submitted' to bceid users so it will show up on dashboard. 
Comments out logic for supplemental reports because for now we don't need to/can't see supplemental reports
=> fix: ZEVA 414 - missing dashboard alert for Recommended Model Year Reports

backend/api/serializers/model_year_report.py, frontend/src/compliance/AssessmentContainer.js, frontend/src/compliance/components/AssessmentDetailsPage.js
fix: adds cancelConfirmation function to return to supplier button, which passes a list of all modules to the backend. On the backend it iterates through the list and deletes the corresponding confirmations from the database.
=> fix: ZEVA 420 - IDIR analyst return MY report to suppler, set all tabs to draft/unchecked 

backend/api/viewsets/model_year_report.py, frontend/src/compliance/AssessmentEditContainer.js, frontend/src/compliance/components/AssessmentDetailsPage.js, frontend/src/compliance/components/AssessmentEditPage.js, frontend/src/compliance/components/AssessmentSupplierInformationMakes.js
fix: backend was saving records for changes when save button was clicked even though no changes were being made. I updated the patch so it checks what is being passed against the last saved records before it makes or updates the record.
feature: frontend - disables save button if no changes have been made since last save
fix: updates handleDeleteMake function so it is not mutating makes
=> fix: ZEVA 415 - Change Log Showing With No Changes Made

backend/api/serializers/sales_submission.py, frontend/src/credits/components/CreditRequestDetailsPage.js
fix: - updates sales submission comment serializer, switches to_govt flag to false in filter for bceid users so they only receive comments that are NOT meant for internal users
-removes !isGovernment in condition for displaying comments to supplier (idir users should see their own comments)
- changes variable names for comment arrays in frontend from transferCommentsIdir etc to submissionCommentsIdirOnly so its more clear what the comments are and who they are meant for -adds bold headers to comment arrays so idir users can see which comments are which
=> Fix: ZEVA 402 - Credit application rejection - comments not visible to supplier (or idir)

frontend/src/supplementary/components/SupplementaryDetailsPage.js
fix: adds directorAction into condition for displaying 'return to analyst' button
if user is an analyst and the status is either 'submitted' or 'returned' the analyst may click the button to return the report to the supplier
if the user is a director and the status is 'recommended' they may click the button to return the report to the analyst
=> fix: zeva 446 - remove return to analyst button from analyst view on supplementary report

backend/api/models/sales_submission_content.py
reduces erroneous 21 errors
- adds a condition on the filter that removes any records where the submission timestamp is later than the timestamp of the current submission. This way, anything that comes through later than the current submission does not affect the calculated field.
=> fix: Zeva 443 - 21 error on old submissions

backend/api/serializers/vehicle.py, backend/api/viewsets/vehicle.py, frontend/src/vehicles/components/VehicleListTable.js
adds vehicleListSerializer so that vehicle list is returned faster, uses serializer method fields to return just necessary data rather than calling other serializers that return data that is not needed
=> chore: ZEVA 468 - Vehicle model list page loads slowly

frontend/src/compliance/components/ComplianceObligationDetailsPage.js, frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js, frontend/src/compliance/components/SupplierInformationDetailsPage.js
-changes how action bar and checkboxes are conditionally rendered, so it now does not render if the report has been submitted, assessed, or reassessed
=> fix: zev 449 -  Hide button bar on MY report after submit

backend/api/serializers/organization.py, frontend/src/app/__tests__/router.test.js, frontend/src/app/components/Unverified.js, frontend/src/app/router.js, frontend/src/organizations/components/VehicleSupplierEditForm.js
- update serializer on organization now sets all users to inactive when organization is set to inactive
- added unverified user page with logout
- added router testing for unverified user page
=> Feat: Setting supplier inactive disables all supplier users - ZEVA 465

frontend/src/app/components/CreditTransactionTabs.js, frontend/src/app/router.js, frontend/src/creditagreements/components/CreditAgreementsListTable.js, frontend/src/credits/components/CreditTransfersListTable.js
fix: adds conditions to getprops in agreement list table, and in router on frontend, and for displaying agreements tab (only idir should see it),
chore: adds maxWidth to shortname of seller
fix: removes extra transaction column, adds condition for displaying
=> fix: zeva 461 - credit agreements issues

.gitignore, frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js, frontend/src/supplementary/SupplementaryContainer.js
-catches null values for sales, credit activity, etc on the frontend and replaces them with the original values from the model year report when posting to supplemental_report_credit_activity
=> fix - ZEVA 509 - Supplementary report - can't null out fields

backend/api/services/model_year_report.py, backend/api/viewsets/credit_request.py, backend/api/viewsets/model_year_report.py, backend/api/viewsets/vehicle.py
- Added checks for patch requests to avoid emails being sent out on comments being posted or general saving happens.
- Added logic for emails to be sent out when model year reports are issued for assessment or reassessment.
- Added logic for emails to be sent out when ZEV models are approved.
=> Email Notifications Bug Fix - 1265

backend/api/services/model_year_report.py, backend/api/viewsets/model_year_report_consumer_sales.py, frontend/src/compliance/components/ComplianceReportAlert.js
fix: adds RETURNED and RECOMMENDED statuses to ComplianceReportAlerts, shares case with submitted
fix: adds recommended to condition for displaying validation_status in consumer sales so it won't show up on network tab
fix: adds some logic on the model_year_report_statuses service for how RECOMMENDED and RETURNED reports are passed to frontend
=> fix: ZEVA 1306 - MY Report status message error

frontend/src/supplementary/components/CreditActivity.js, frontend/src/supplementary/components/SupplementaryAnalystDetails.js, frontend/src/supplementary/components/SupplementaryCreate.js, frontend/src/supplementary/components/SupplementaryDirectorDetails.js, frontend/src/supplementary/components/SupplementarySupplierDetails.js
newLdvSales values that were 0 were given a 'false' value and not being passed in ternary for CreditActivity props.
Rather than update the ldvSales values on every component, this updates it on just CreditActivity and removes newLdvSales from the other components
=> fix: zeva-1365 - allow Zero value in model year LDV Sales field

backend/api/serializers/model_year_report.py, frontend/src/supplementary/components/CreditActivity.js, frontend/src/supplementary/components/SupplementaryAnalystDetails.js, frontend/src/supplementary/components/SupplierInformation.js, frontend/src/supplementary/components/__tests__/SupplementaryAnalystDetails.test.js
fixes first two items on bug list plus includes a test that can be added to as I go 
when a reassessment is in draft on the idir side, and bceid opens the model year report, currently it opens a new supplementary. It should open the model year report.
as a bceid user
when i open a model year report that was assessed
it should open the assessed report (even if government is in the process of making a reassessment)
if a reassessment is in draft the input boxes should be enabled (currently disabled)
=> partial fix: Zeva 1432 - Supplementary Bugs

backend/api/serializers/model_year_report.py, backend/api/viewsets/model_year_report.py, frontend/src/supplementary/components/SupplementaryAnalystDetails.js, frontend/src/supplementary/components/SupplementaryDirectorDetails.js, frontend/src/supplementary/components/SupplementarySupplierDetails.js, frontend/src/supplementary/components/__tests__/SupplementaryAnalystDetails.test.js
disable all inputs for director if not recommended, the only thing director should update is the message to supplier
as a bceid user, i should be able to delete a draft reassessment
as an idir user, if i open a model year report that has a supplementary draft saved by bceid, it should not display that draft information to me
comment input from director to analyst appears only for recommended status
=> fix: zeva 1432 - part 3

openshift/run-test-script.sh
This is a script that takes a .sql script, uploads it into the openshift zeva test pod, and executes it. It can be used for resetting the supplementary stuff on test!
=> feat: zeva-1339 - script for running db scripts on test

frontend/src/app/components/EditableCommentList.js, frontend/src/supplementary/components/SupplementaryAnalystDetails.js, frontend/src/supplementary/components/SupplementaryDirectorDetails.js
-adds enableEditable boolean to comment list
- makes comments visible for all report statuses but not editable if user is director and status is anything but recommended, or not editable if  user is analyst and status is recommended or assessed
=> fix: ZEVA 1490 - reassessment comment array/input for director and analyst

frontend/src/compliance/components/ComplianceHistory.js, frontend/src/supplementary/components/SupplementaryAnalystDetails.js, frontend/src/supplementary/components/SupplementaryDirectorDetails.js
- for idir users the tab color is now correct when clicking through history to get to reassessent
- bottom bullet is removed for reassessments that have been recommended/issued (no longer shows when draft was saved)
-director name now shows up in history for assessed reassessments, for idir users only (previously showed up as assessed by government...)
-shows attachments to idir users
-changes text on headers for history components (ie Reassessment - REASSESSED instead of model year report Reassessment - reassessed, etc)
=> fix: Zeva 1490 history component bugs and changes

backend/api/models/organization.py, backend/api/serializers/account_balance.py, backend/api/serializers/model_year_report_assessment.py, backend/api/serializers/model_year_report_assessment_comment.py, backend/api/serializers/model_year_report_compliance_obligation.py, backend/api/viewsets/model_year_report_compliance_obligation.py, frontend/src/compliance/components/ConsumerSalesLDVModelTable.js
fix: changes organization model method to use transactions to calculate balance rather than acount balance table
chore: removes unused serializer from compliance obligation (there are still some unused serializers here...
chore: removes unused references from some files
fix:adds check for array length in consumer sales ldv model table (was causing error if list length is 0)
=> fix: ZEVA - Incorrect credit balance being displayed on organization page #1517

backend/api/serializers/model_year_report.py, backend/api/viewsets/model_year_report.py, frontend/src/supplementary/components/SupplementaryAnalystDetails.js
fix: changes returned reports in the list page to say 'reassessment returned' instead of 'supplementary returned'
fix: comments on returned supplementary were not visible, the viewset was passing 0 as the supplementary id for returned status, it now passes the correct id so comments display.
=> fix: zeva 1567 - comments not visible and list page showing supplemental returned

frontend/src/compliance/components/AssessmentDetailsPage.js, frontend/src/compliance/components/NoticeOfAssessmentSection.js, frontend/src/supplementary/components/ReassessmentDetailsPage.js
-fix: address reassessment addresses to reassessment page / refactors notice of assessment
-splits up records/service addresses in the details page so that they are handled separately
=> fix zeva 1567 continued - service/records address changes from reassessment not appearing on reassessment page

frontend/src/supplementary/components/SupplementaryAnalystDetails.js, frontend/src/supplementary/components/__tests__/SupplementaryAnalystDetails.test.js
@AlexZorkin I'm not too sure about this test : // as an analyst
// if i view a supplemental report in submitted status
// I should be able to view a editable version of all 3 tabs
In the code, it looks like the "supplemental" and "reassessment" tabs should be non-editable when a supplemental report is in "submitted" status... I wrote the tests according to how they were described in the card, so the tests that deal with these 2 cases will fail.
=> chore: zeva-1499 - SupplementaryAnalystDetails unit tests

frontend/src/supplementary/components/SupplementaryAnalystDetails.js, frontend/src/supplementary/components/SupplementaryDirectorDetails.js
fix: updates logic so that penalty is displayed for director and analyst in the written description for recommended/assessed reports as well as radio descriptions (for draft, returned, etc)
chore: removes formattedPenalty to reduce amount of code
=> fix: zeva 1567 reassessment penalty showing up as $0

frontend/src/dashboard/DashboardContainer.js
fix: moves setLoading(false) to the end of the getDashboard function, to happen after it finishes, adds a setLoading(true) to the beginning as well
=> fix: ZEVA - Dashboard Loading Performance Issues for Director Role - 1612

frontend/src/compliance/components/AssessmentDetailsPage.js
- Added logic on model year reports to clear the input field if the penalty radio button is not selected
=> Fix: Clear Penalties when Assessment decision changes - 1635

backend/api/serializers/model_year_report_noa.py, frontend/src/compliance/components/ComplianceHistory.js
- Removed exclude for draft statuses as a government user
- Added logic to properly capture when a report is returned to a supplier in the history.
=> Feat: Model Year Report Returned History Timestamp #1287

backend/api/viewsets/model_year_report.py
- Modified logic to exclude supplemental report from the reporting timeline if a reassessment has started for it
=> Fix - Reassessment/Supplementary Report Timeline #1868

frontend/src/compliance/components/ComplianceObligationDetailsPage.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js, frontend/src/compliance/components/SupplierInformationDetailsPage.js
- Disable save button on click to prevent multiple save actions from firing
=> Fix - Draft Report Save Issue #1851

.github/readme.md, .github/workflows/dev-build.yaml, .github/workflows/release-build.yaml, backend/api/serializers/credit_transfer.py, backend/api/services/credit_transaction.py, backend/api/services/model_year_report_ldv_sales.py, backend/api/services/supplemental_report.py, backend/api/viewsets/model_year_report.py, backend/api/viewsets/model_year_report_compliance_obligation.py, frontend/package.json, frontend/src/app/routes/Compliance.js, frontend/src/compliance/components/AssessmentDetailsPage.js, frontend/src/compliance/components/ComplianceHistory.js, frontend/src/compliance/components/ComplianceObligationDetailsPage.js, frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js, frontend/src/compliance/components/SupplierInformationDetailsPage.js, frontend/src/credits/components/TransferFormRow.js, frontend/src/supplementary/SupplementaryContainer.js, frontend/src/supplementary/components/SupplementaryDirectorDetails.js
=> Tracking pull request to merge release-1.49.0 to master

frontend/src/dashboard/components/ActionsBceid.js
- Updated dashboard link to not filter under a specific circumstance and instead link to the general list
=> Fix - Dashboard Link #1357

backend/api/viewsets/credit_request.py
adds recommended and checked submissions to the queryset filter if the bceid user searches anything that matches submitted
=> fix ZEVA 2091: credit application table filter missing some submitted records

frontend/src/app/app.js
- Setting the default timezone to PST at the top of the application to display timestamps correctly.
=> Feat: Timezones Default PST #2125

backend/api/services/icbc_upload.py
adds effective/expiration date to model year object creation so those new years can be included in the ingest_sales_spreadsheet script
=> fix: 2163 - emily - sales spreadsheet model years missing

backend/api/serializers/sales_submission.py, backend/api/serializers/sales_submission_comment.py, backend/api/serializers/vehicle.py, backend/api/serializers/vehicle_comment.py
removes commentors name from vehicle and credit requests
if commenter is idir and current user is bceid:
show 'government user'
if commenter is bcied or current user is idir:
show details
=> Feat 2206 - Prevent commentator's name from displaying when updating information from comment

frontend/src/app/utilities/getModelYearReportCreditBalances.js
=> ZEVA 2216: Fix - Rounding Error Between Credit Transaction Line Items and Detailed Credit Balance

backend/api/viewsets/credit_request.py
adds context to update comment
=> fix: comment edit

backend/api/mixins/user_mixin.py, backend/api/serializers/credit_agreement.py, backend/api/serializers/credit_agreement_comment.py, backend/api/serializers/credit_transfer.py, backend/api/serializers/credit_transfer_comment.py, backend/api/serializers/model_year_report.py, backend/api/serializers/model_year_report_assessment.py, backend/api/serializers/model_year_report_assessment_comment.py, backend/api/serializers/model_year_report_confirmation.py, backend/api/serializers/model_year_report_history.py, backend/api/serializers/model_year_report_noa.py, backend/api/serializers/model_year_report_supplemental.py, backend/api/serializers/sales_submission.py, backend/api/serializers/sales_submission_comment.py, backend/api/services/model_year_report.py, backend/api/viewsets/credit_agreement.py, backend/api/viewsets/model_year_report.py, backend/api/viewsets/model_year_report_consumer_sales.py, frontend/src/credits/components/CreditTransfersDetailsPage.js
creates user mixin for displaying update or create users as a specific way depending on whether they are government or not and whether the request user is government or not
refactors code to use this mixin for both commenters and other update/create users
=> Chore/2267 - remove commentator's name

backend/api/serializers/model_year_report_supplemental.py, backend/api/viewsets/model_year_report.py, frontend/src/creditagreements/components/CreditAgreementsAlert.js, frontend/src/users/components/UserDetailsForm.js
fix: updates credit agreement alert to use displayname
fix: grabs supplementary comments also using supplementary id instead of just reassessment id
chore: adds empty strings to default value in user details form so there are  no console errors if there are blank fields
chore: removes old print statement
=> fix: supplementary comment not appearing, agreement alerts missing name of update user

frontend/src/app/components/VehicleSupplierTabs.js, frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js
fix: adds check for comments before rendering div with outline so there isnt an empty box when agreements dont have comments
chore: modifies proptypes in vehicle supplier tabs due to console messages appearing
=> zeva minor credit agreements comment display bug 

backend/api/services/sales_spreadsheet.py, frontend/src/app/components/FileDropArea.js
spreadsheets with duplicate vins are rejected with error message during submission
=> task: 2363 Flagging Duplicate VINs in BCeID Spreadsheet Uploads to Prevent Error 31 (duplicate VINs)

frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js
-adds navigation tabs to credit agreement details
-prettier linting
look at commit 1 for details of the actual change
=> task: 2338 - credit transaction tabs on credit agreement details pages

frontend/src/compliance/components/ConsumerLDVSales.js
fix: changes sales input to be numerical instead of text to reduce user error
possibly the error was happening because the user added a comma into the input, now it will not accept non numeric values
=> fix: assessment edit bug 

frontend/src/compliance/ConsumerSalesContainer.js, frontend/src/compliance/components/ComplianceReportSignOff.js, frontend/src/compliance/components/ConsumerSalesDetailsPage.js
Forecast Report - checkbox only appears for MY2024 and later.
Consumer ZEV Sales Information - should remain
Older reports (MY2020–2022) don’t show the Forecast Report checkbox.
=> fix: 2408 - confirmation checkbox for sales forecast

frontend/src/creditagreements/__tests__/CreditAgreementDetailsPage.test.js
Fix failing tests for `CreditAgreementDetailsPage.test.js`. The `<Router>` was missing causing `<Link>` to throw errors.
=> Fix failing tests for CreditAgreementDetailsPage

backend/api/models/organization.py
After the supplier info page of the compliance report is saved as a draft, no further changed can be saved because the "patch" API would return status 500.  The reason behind is that the "year" is a string, which cannot be compared with the number 2024. (This mainly happen in line 141, but I changed the similar line 125 as well for save.)
This is related to the "red error message" described in #2440.
While the changes described in #2440 can prevent this bug being triggered, the solution also prevent user from saving a draft report. Hence, the changes proposed in #2440 (and related issue #2439) would need to be re-discussed among the PO, designer, and the business.
=> 2439, 2440 Bug-fix: "year" at backend may not be int

frontend/package.json
This PR removes the unused react-keycloak library, which breaks npm-install when declared alongside the updated keycloak-js library
=> remove unused react keycloak

frontend/src/app/css/App.scss
Some tooltips were overflowing on a single line when it was over 500px, this ensures that it will break the word and flow down.
=> fix overflowing tooltip

backend/api/services/sales_submission.py, backend/api/viewsets/credit_request.py, frontend/src/credits/components/CreditRequestAlert.js
task:
removes deleted records from exclusion filter in credit request) queryset so deleted submissions will show up for idir users. This may need to be modified as IDIR users might not want to see submissions that were Draft->Deleted.
updates populate_already_awarded_warnings funtion to  not include Deleted submissions when creating icbc warnings
=> TASK: deleted submissions visible to IDIR users, deleted VINs no longer trigger duplicate warning
