bcgov/zeva

frontend/src/index.js

A typo in a previous PR broke the frontend. This fixes it.

Fix import typo

---

dockerfiles/envoy/envoy.yaml
frontend/notifications.js
frontend/package.json
frontend/src/app/NotificationsClient.js
frontend/src/app/PageLayout.js
frontend/start.js
k8s-frontend.yaml
k8s-frontproxy.yaml

- Websockets support running alongside webpackDevServer
- Basic client-side support
- `frontend` pods needs port 5002 open for inbound TCP connection from `envoy`

Websockets Support

---

.circleci/config.yml
frontend/src/app/config.js
openshift/templates/envoy/envoy-bc.yaml
openshift/templates/envoy/envoy-dc.yaml
openshift/templates/frontend/create.sh
openshift/templates/frontend/frontend-dc.yaml
openshift/templates/nsp/quickstart-nsp.yaml
openshift/templates/python-backend/create.sh

Update frontend time zone to PST
Correct template settings
Add three generic policys

Update Openshift Templates

---

frontend/src/app/History.js
frontend/src/app/css/App.scss
frontend/src/app/css/ReactTable.scss
frontend/src/app/css/index.scss
frontend/src/app/router.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/organizations/components/OrganizationListPage.js
frontend/src/organizations/components/OrganizationsTable.js
frontend/src/organizations/components/UsersTable.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js
frontend/src/organizations/components/VehiclesTable.js

for ZEVA#15
Changelog:
- Added styling for action-bar
- Added icons to buttons
- Added Detail Page for Vehicle Suppliers
- Changed Router from BrowserRouter
- Table now has clickable rows

View Vehicle Supplier Details

---

backend/wsgi.py
backend/zeva/settings.py

We're replicating TFRS with this. So just copying the files from TFRS

Added wsgi to make gunicorn to work

---

backend/api/fixtures/operational/0001_add_vehicle_makes.py
backend/api/fixtures/operational/0004_add_model_years.py
backend/api/fixtures/operational/0007_add_organizations.py

ZEVA-60
Changelog:
- Added the list of organizations migration
- Removed 2017 and 2018 from the model year migration
- Added new vehicle makes
- Reorganized the code to become more readable

Add Organizations

---

frontend/src/app/Login.js
frontend/src/app/PageLayout.js
frontend/src/app/app.js
frontend/src/app/components/Navbar.js
frontend/src/app/css/Navbar.scss

- Adjust `Login` frontend component to use Keycloak API
- Add Logout button to Navbar

Fix login, add logout button

---

backend/api/fixtures/development/0000_add_sample_users.py
frontend/src/app/Login.js
frontend/src/app/NotificationsClient.js
frontend/src/app/PageLayout.js
frontend/src/app/app.js
frontend/src/app/components/Navbar.js
frontend/src/app/css/Navbar.scss
frontend/src/app/utilities/props.js
frontend/src/dashboard/DashboardContainer.js
frontend/src/dashboard/components/Balance.js
frontend/src/dashboard/components/DashboardPage.js
frontend/src/dashboard/components/OrganizationDetails.js
frontend/src/dashboard/components/UserSettings.js
frontend/src/organizations/OrganizationDetailsContainer.js
frontend/src/organizations/OrganizationListContainer.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/organizations/components/OrganizationDetailsPage.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js
frontend/src/vehicles/VehicleAddContainer.js
frontend/src/vehicles/VehicleDetailContainer.js
frontend/src/vehicles/VehicleListContainer.js

- Move proptypes for common things to a utility file to avoid boilerplate
- linting
- use `implicit` oauth2 flow

Followup: Code cleanup for login fix

---

frontend/src/app/NotificationsClient.js
frontend/src/app/components/Navbar.js
frontend/src/app/css/Sales.scss
frontend/src/app/css/index.scss
frontend/src/app/router.js
frontend/src/app/routes/Sales.js
frontend/src/organizations/OrganizationDetailsContainer.js
frontend/src/organizations/OrganizationListContainer.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/sales/SalesDetailsContainer.js
frontend/src/sales/SalesListContainer.js
frontend/src/sales/components/SalesDetailsPage.js
frontend/src/sales/components/SalesDetailsTable.js
frontend/src/sales/components/SalesListPage.js
frontend/src/sales/components/SalesListTable.js
frontend/src/vehicles/VehicleAddContainer.js
frontend/src/vehicles/VehicleDetailsContainer.js
frontend/src/vehicles/VehicleListContainer.js
frontend/src/vehicles/components/ActionBarGov.js
frontend/src/vehicles/components/VehicleList.js

ZEVA-64
Changelog:
- Added SalesDetailsContainer 
- Added SalesListContainer
- Removed unused imports
- Renamed VehicleDetailContainer to VehicleDetailsContainer

Added Sales List and Sales Detail front-end

---

backend/api/fixtures/test/0000_add_users.py

Changelog:
- Updated Emily's IDIR
- Added Rob
- renamed filename

Added Rob and Renamed test migration so there's only one 0001

---

backend/api/viewsets/vehicle.py

Changelog:
- The system should now only load makes associated to your organization

Automatically Filter Makes When Creating a New Vehicle

---

backend/api/fixtures/operational/0005_add_organizations.py

Changelog:
- Removed some Organizations
- Split up some organizations like Renault

Updated the organization fixture to split up some organizations

---

frontend/src/app/app.js
frontend/src/app/components/ErrorHandler.js
frontend/src/app/components/StatusInterceptor.js
frontend/src/app/router.js

Changelog:
- Adds a componentDidCatch so that js errors don't just render a blank page
- Added a catch for fetching the user's information so that it doesn't get stuck in a loading icon

Error Handling for Front-end

---

backend/api/fixtures/test/0004_add_bceid_users.py

Changelog:
- Similar to the add users fixture, this adds "us" as bceid users with random organizations

Fixtures for Test BCEID Users

---

backend/api/management/commands/load_ops_data.py

- Removed a print statement that is possibly causing the error experienced under Openshift

Ops Data Script Fix

---

backend/api/fixtures/development/0000_add_sample_users.py
backend/api/fixtures/operational/0000_add_government_organization.py
backend/api/fixtures/operational/0001_add_vehicle_makes.py
backend/api/fixtures/operational/0002_add_vehicle_classes.py
backend/api/fixtures/operational/0003_add_vehicle_fuel_types.py
backend/api/fixtures/operational/0004_add_model_years.py
backend/api/fixtures/operational/0005_add_organizations.py
backend/api/fixtures/test/0000_add_users.py
backend/api/fixtures/test/0001_add_plugin_hybrid_vehicles.py
backend/api/fixtures/test/0002_add_battery_electric_vehicles.py
backend/api/fixtures/test/0004_add_bceid_users.py
backend/api/management/commands/load_ops_data.py

- Fixes for operational data scripts
- Runs now actually idempotent
- Fixed a possible Python 3.6 compatibility issue

Add run preconditions, possibly python 3.6 fix

---

backend/api/models/organization.py
backend/api/serializers/credit_transction.py
backend/api/serializers/organization.py
backend/api/tests/test_credit_transactions.py
backend/api/tests/test_sales.py
backend/api/urls.py
backend/api/viewsets/credit_transaction.py

- Added Credit  Transaction views, serializers, associated test cases
- Modified Organization serializer to report balances
- Fixes sales test cases (all tests pass now)
JIRA ZEVA-106

Backend work for Credit Table

---

frontend/package.json
frontend/src/credits/components/__tests__/CreditTransactions.test.js

-added jest-dom to package.json
-added simple render test to credit transaction component

ZEVA-97 - front end testing

---

backend/api/services/keycloak_api.py

It's failing to fetch the attributes for the user and I'm trying to figure out why it only does that in the server

Debug Code for Keycloak

---

openshift/templates/config/configmap.yaml
openshift/templates/frontend/frontend-dc-release.yaml
openshift/templates/frontend/frontend-dc.yaml

Changelog:
- added to config map
- added to deployment templates

ZEVA-112 Added Logout Environment Variables

---

frontend/src/credits/components/CreditTransactions.js
frontend/src/credits/components/__tests__/UploadVerificationData.test.js
frontend/src/vehicles/components/__tests__/VehicleForm.test.js

-fixed error in credit transactions table
-added test file for upload verification data

Icbctests - no jira ticket

---

frontend/src/app/components/Navbar.js
frontend/src/app/components/VehicleSupplierTabs.js
frontend/src/app/router.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/organizations/components/OrganizationsTable.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js
frontend/src/organizations/components/VehicleSupplierZEVListPage.js

-added supplier details back to nav bar
- updated supplier list
-added tabs to individual suppliers (not working yet)

ZEVA-134 view organizations list

---

backend/api/keycloak_authentication.py
backend/api/services/keycloak_api.py
backend/api/tests/test_credit_transactions.py
backend/requirements.txt

Changelog:
- Fixed keycloak automapping
- Linting fixes
- Unit test fixes

ZEVA-132 Fixed Automapping for Keycloak

---

backend/api/serializers/vehicle.py
frontend/src/app/css/VehicleSuppliers.scss
frontend/src/vehicles/VehicleDetailsContainer.js
frontend/src/vehicles/components/VehicleValidatePage.js

Changelog:
- New look for IDIR users when viewing vehicles
- Validate functionality should now be working
- Credit Class and Credit Value are automatically calculated, but will not display for BCEID users until the vehicle is validated
Note: there's currently no link to view a submitted vehicle. You have to navigate to /vehicles/{id} manually for now

ZEVA-136: IDIR users can validate submitted vehicles

---

backend/api/viewsets/organization.py
frontend/src/app/routes/Organizations.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/organizations/components/SalesSubmissionListTable.js
frontend/src/organizations/components/UsersTable.js
frontend/src/organizations/components/VehicleSupplierSalesListPage.js
frontend/src/organizations/components/VehicleSupplierUserListPage.js
frontend/src/organizations/components/VehicleSupplierZEVListPage.js
frontend/src/vehicles/components/VehicleListTable.js

Changelog:
- Organization User List
- Organization Sales List
- Connected New User
- Connected Validate Model screen

Release Candidate for Sprint 10

---

frontend/src/app/components/Navbar.js
frontend/src/organizations/components/OrganizationDetailsPage.js

commented out credits, org class, and class on organization details page and navbar

ZEVA-146: disable details/info

---

frontend/src/app/components/VehicleSupplierTabs.js
frontend/src/app/router.js
frontend/src/organizations/VehicleSupplierCreditTransactionListContainer.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/organizations/VehicleSupplierEditContainer.js
frontend/src/organizations/VehicleSupplierModelListContainer.js
frontend/src/organizations/VehicleSupplierUserListContainer.js
frontend/src/organizations/components/VehicleSupplierEditForm.js

Changelog:
- Containers are now split up into their respective functions: Details, Edit, Users and Credit Transactions
- ESLint fixes

ZEVA-147: Split the Details Container into multiple containers

---

backend/api/serializers/vehicle.py

Changelog:
- Now checks the credit value and class and saves it when the vehicle is validated

Save Credit Value and Class upon Validating

---

backend/api/models/user_profile.py
backend/api/serializers/organization.py
backend/api/serializers/organization_address.py
backend/api/serializers/permission.py
backend/api/serializers/user.py
backend/api/viewsets/organization.py
frontend/src/app/components/Navbar.js
frontend/src/app/components/TextInput.js
frontend/src/app/router.js
frontend/src/app/utilities/parseErrorResponse.js
frontend/src/organizations/VehicleSupplierEditContainer.js
frontend/src/organizations/components/VehicleSupplierEditForm.js
frontend/src/users/UserAddContainer.js
frontend/src/users/UserEditContainer.js
frontend/src/users/components/UserDetailsForm.js

Changelog:
- Backend validation is now being caught and displayed by the front-end
- Consolidated some serializers into one
- Removed permission checking from keycloak and use the one in our system instead
- Further code-clean up

ZEVA-157: Form Validation

---

backend/api/fixtures/test/0004_add_user_roles.py

Changelog:
- This fixture is to give our accounts roles so we can use it in dev and test

User Roles Fixture

---

frontend/src/app/app.js
frontend/src/app/router.js

Changelog:
- Changed flow to hybrid
- No longer using interceptors. Instead, we update the token when it's expired.

Token Renewal Changes

---

frontend/src/app/components/ErrorHandler.js
frontend/src/app/components/Navbar.js
frontend/src/app/router.js

Changelog:
- Now catching errors above 400 and displaying an error screen as opposed to being stuck at loading screen

Better Way of Handling Error

---

backend/api/migrations/0051_auto_20200529_1158.py
backend/api/migrations/0052_auto_20200529_1200.py
frontend/src/app/router.js

Changelog:
- Fixed migration conflicts
- Fixed a bug with the interceptor not throwing the errors back so 400 errors can be caught

Fixed migration conflicts

---

backend/api/serializers/sales_submission.py
backend/api/serializers/user.py

Changelog:
- Fixed a bug where Sales was throwing a 500 error as update_user is no longer using an id, but instead a username instead

Bug fix for Update User

---

backend/api/services/icbc_upload.py
backend/api/services/parser.ipynb
frontend/package-lock.json
frontend/package.json
frontend/src/app/components/AutocompleteInput.js
frontend/src/app/css/Form.scss
frontend/src/vehicles/VehicleAddContainer.js
frontend/src/vehicles/components/VehicleForm.js

-added capitalization to make and model in registration data
-added jupyter file for exploring data
-started autofill component (not finished)

ZEVA 170 - Data Exploration

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/components/AutocompleteInput.js
frontend/src/app/css/Autocomplete.scss
frontend/src/app/css/Form.scss
frontend/src/app/css/index.scss
frontend/src/vehicles/VehicleAddContainer.js
frontend/src/vehicles/components/VehicleForm.js

-uses react-autosuggest
-css to match zeva styling
-creates list from vehicles returned for that organization and uses those as suggested options

ZEVA 156 - Autocomplete

---

frontend/src/vehicles/components/VehicleForm.js

Changelog:
- Fix an error where Add Vehicle no longer works because of some calls for the file uploader

Fixed Add vehicle running into errors

---

backend/api/serializers/organization.py
backend/api/serializers/vehicle.py
frontend/src/vehicles/components/VehicleForm.js

Changelog:
- Added Required=False to make sure that attachments are optional
- Fixed an issue where create_user was throwing an error

Followup Fix

---

backend/api/models/vehicle_statuses.py
frontend/src/app/components/DetailField.js
frontend/src/app/utilities/formatStatus.js
frontend/src/users/components/UserDetailsForm.js
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleListTable.js

Changelog:
- Added Changes Requested status
- Added a formatting for the status in the front-end so its better capitalized

ZEVA-152 Added Changes Requested status

---

backend/api/serializers/vehicle.py
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js
frontend/src/vehicles/components/VehicleHistoryTable.js
frontend/src/vehicles/components/VehicleValidatePage.js

Changelog:
- File uploader only shows up if the status is Changes Requested
- Fixed update user not populating in Vehicle History
- Changed button text so its "Submit" and not "Set Status to SUBMITTED"

File uploader only shows up when changes are requested

---

backend/api/fixtures/test/0000_add_users.py
backend/api/fixtures/test/0005_add_bceid_user_roles.py
backend/api/serializers/organization.py
backend/api/serializers/user.py
backend/api/services/user.py
frontend/src/app/components/Navbar.js
frontend/src/app/css/Dashboard.scss
frontend/src/dashboard/components/Administration.js
frontend/src/dashboard/components/DashboardPage.js
frontend/src/dashboard/components/UserSettings.js
frontend/src/users/UserEditContainer.js
frontend/src/users/components/UserDetailsForm.js

Changelog:
- Updated test fixtures so it reflects more accurately for our accounts
- update_roles service
- Admin section in the dashboard
- Admin Page
- Allowed editing of IDIR users
- Update permissions for editing and updating roles

ZEVA-171 Edit IDIR Users

---

backend/api/management/commands/generate_sales_template.py
backend/api/management/commands/ingest_sales_data.py
backend/api/models/record_of_sale.py
backend/api/services/sales_spreadsheet.py
backend/api/viewsets/record_of_sale.py
frontend/src/app/routes/Sales.js
frontend/src/sales/components/SalesSubmissionPage.js

Changelog:
- Suppliers now need to provide model year, make and model name
- No longer split between vehicle models
- Instructions on the first sheet
- Update parser
- Removed year dropdown

ZEVA-173 Merge Sales Sheets into One

---

backend/api/serializers/vehicle.py
frontend/src/vehicles/VehicleListContainer.js
frontend/src/vehicles/components/ActionBarGov.js
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleList.js
frontend/src/vehicles/components/VehicleListTable.js

-Remove Validate checkbox column and save button
-Update filtering buttons so they filter / clear
-all ZEV statuses except "draft" appear on table
-added new columns for body, weight, supplier

ZEVA 172:  IDIR ZEV model page updates

---

backend/api/models/sales_submission.py
backend/api/tests/test_credit_transactions.py
backend/api/tests/test_sales.py

Changelog:
- Fixed unit tests (broken by new column in the transaction table
- Added tests for Validation Status

Additional Unit Test

---

backend/api/fixtures/test/0001_add_plugin_hybrid_vehicles.py
backend/api/fixtures/test/0002_add_battery_electric_vehicles.py
backend/api/models/__init__.py
backend/api/models/credit_class.py
backend/api/models/credit_transaction.py
backend/api/models/credit_transaction_type.py
backend/api/models/fixture_migration.py
backend/api/models/icbc_vehicle.py
backend/api/tests/test_load_ops_data.py
frontend/package.json
frontend/webpack.config.js

Changelog:
- Updated test so it works better with Python 3.6.9
- Pylint fixes
- Added a condition for changing the mode to production for webpack

ZEVA-167: Webpack Production

---

backend/api/serializers/icbc_registration_data.py
backend/api/serializers/icbc_vehicle.py
backend/api/serializers/record_of_sale.py
frontend/src/app/css/ReactTable.scss
frontend/src/credits/SalesSubmissionDetailsContainer.js
frontend/src/credits/components/SalesListTable.js

-added serializer to check sales vin against icbc vin
-added warnings (11) or checkmarks if there is no match or a match
-added red background if no match

ZEVA 185 - Validate vins

---

frontend/package.json
frontend/src/app/components/__tests__/StatusInterceptor.test.js
frontend/src/app/utilities/__tests__/formatStatus.test.js
frontend/src/app/utilities/__tests__/getCreditClass.test.js
frontend/src/app/utilities/__tests__/getFileSize.test.js
frontend/src/app/utilities/__tests__/parseErrorResponse.test.js
frontend/src/credits/components/__tests__/UploadVerificationData.test.js
frontend/src/users/components/__tests__/UserDetailsForm.test.js
frontend/src/vehicles/components/__tests__/ActionBarGov.test.js
frontend/src/vehicles/components/__tests__/VehicleForm.test.js

added tests for basic utilities and components
edited older tests to have fewer errors (actionbar, userDetailsForm)

frontend tests

---

backend/api/models/icbc_upload_date.py
backend/api/serializers/icbc_upload_date.py
backend/api/services/icbc_upload.py
backend/api/viewsets/icbc_verification.py
frontend/package.json
frontend/src/app/css/ReactTable.scss
frontend/src/app/routes/ICBCVerification.js
frontend/src/app/utilities/upload.js
frontend/src/credits/CreditRequestDetailsContainer.js
frontend/src/credits/CreditsContainer.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/SalesListTable.js
frontend/src/credits/components/SalesSubmissionDetailsPage.js
frontend/src/credits/components/UploadVerificationData.js
frontend/src/credits/components/__tests__/SalesListTable.test.js

-added 21 error and formatting for year mismatch
-fixed bug with icbc upload calendar
-updated model description for upload dates
-started sales list table test, not yet finished

zeva 198 - error code for year mismatch

---

backend/api/serializers/account_balance.py
backend/api/serializers/credit_transaction.py
backend/api/serializers/icbc_vehicle.py
backend/api/serializers/vehicle_comment.py
backend/api/serializers/weight_class.py
backend/api/services/credit_transaction.py
backend/api/viewsets/credit_transaction.py
backend/api/viewsets/submissions.py
frontend/src/app/components/Navbar.js
frontend/src/app/css/Navbar.scss
frontend/src/app/router.js
frontend/src/app/routes/Credits.js
frontend/src/credits/CreditBalanceContainer.js
frontend/src/credits/CreditsContainer.js
frontend/src/credits/components/CreditBalancePage.js
frontend/src/credits/components/CreditBalanceTable.js
frontend/src/credits/components/CreditTransactions.js
frontend/src/credits/components/__tests__/CreditTransactions.test.js

Changelog:
- Backend code to calculate the credit balance details
- Frontend code to display the balance by model year, vehicle class and zev class
- Added serializer for the credit balance
- Added link from the nav bar
- Added link from the credit transaction page

ZEVA-196: Credit Balance Detail

---

backend/api/migrations/0061_auto_20200717_0835.py

Changelog:
- Fixed migration conflicts

Fix migration conflicts

---

frontend/src/credits/CreditTransfersContainer.js
frontend/src/credits/components/CreditTransfersPage.js

fixed transfer partner bug by passing field prop and using that as the selected option

fixed transfer partner bug

---

backend/api/services/credit_transaction.py

Changelog:
- Added Coalesce to make sure that the value returns something and won't cause the calculation to return None

Fixed the credit detail breakdown page

---

frontend/src/vehicles/components/VehicleValidatePage.js

Changelog:
- Changed the check on the comments object so that it enables the validate button based on the comment content

Fixed validate button not enabling

---

frontend/src/app/components/Modal.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditTransfersPage.js
frontend/src/sales/components/SalesSubmissionSignaturesModal.js
frontend/src/sales/components/SalesSubmissionValidationPage.js
frontend/src/vehicles/components/VehicleForm.js
frontend/src/vehicles/components/VehicleValidatePage.js

changed buttons to open modal to confirm choice before submitting changes to database
IDIR
validating a ZEV model;
-Validate ZEV model
-Reject ZEV model
making a request for range information for a zev model;
-Request range change/test results
issuing credits;
-Issue credits to vehicle supplier?
-Recommend rejection of credits?
-Recommend approval of credits?
BCeID
Submitting ZEV model info;
-Submit ZEV model to government?
submitting ZEV sales info;
-Submit credit request to government?
submitting range data
-Submit vehicle model and range test results to government
submitting a credit transfer notice
-Submit credit transfer notice to transfer partner?

ZEVA 207 - modal popup

---

backend/api/services/sales_spreadsheet.py

added instructions for filling out date and updated column name to "Retail Sales Date (yyyy-mm-dd)"

ZEVA 210 - sales upload spreadsheet changes

---

frontend/src/app/components/CreditTransactionTabs.js
frontend/src/credits/CreditsContainer.js
frontend/src/credits/components/UploadVerificationData.js
frontend/src/users/components/UserDetailsForm.js

After phone call with James:
-removed mandatory from phone field
-added icbc upload tab to transactions tabs for idir user

added icbc upload tab to transactions tabs for idir user

---

backend/api/fixtures/test/0006_add_test_users.py

Changelog:
- Adds TEST_IDIR and TEST_BCEID users for functional test

ZEVA 204: Added functional test users

---

frontend/src/app/router.js
frontend/src/app/routes/Organizations.js
frontend/src/organizations/components/OrganizationDetailsPage.js
frontend/src/users/UserAddContainer.js
frontend/src/users/components/UserDetailsForm.js

Changelog:
- Updated IDIR form so it no longer shows bceid fields
- Added "Add User" button

ZEVA-171: Updated IDIR form. add 'Add User' button

---

frontend/src/organizations/components/VehicleSupplierDetailsPage.js

commented out vehicle supplier size from details page

ZEVA218: hide supplier size

---

frontend/src/vehicles/components/ActionBarNonGov.js
frontend/src/vehicles/components/VehicleListTable.js

-changed table headings
-hid download as excel button in bceid action bar

ZEVA 233 - ZEV Models - changes to table headings and hide download

---

frontend/src/dashboard/DashboardContainer.js
frontend/src/organizations/VehicleSupplierEditContainer.js
frontend/src/organizations/components/AddressForm.js
frontend/src/organizations/components/VehicleSupplierEditForm.js

Changelog:
- Minor refactoring on the dashboard axios calls
- ESLint fixes
- Switched Service and Records in the Address Form

ZEVA-259: Switched Service and Records Address

---

frontend/src/app/components/CreditTransactionTabs.js
frontend/src/app/components/Navbar.js
frontend/src/app/components/ReactTable.js

Changelog:
- Changed the url for the credit transaction navigation for IDIR
- Added additional check to react-table
- Credit Transaction tabs should no longer show balance for IDIR

ZEVA-255: Removed Credit Transaction page

---

backend/api/serializers/organization.py
frontend/src/users/UserAddContainer.js

Changelog:
- When creating a user, default status is now Active
- Fixed a bug with the Organization Address edit

ZEVA-251: Set default status to Active when creating a User

---

frontend/src/credits/components/SubmissionListTable.js

Changelog:
- Changed Validated to Issued (front-end only)

ZEVA-250: IDIR Credit Transactions Statuses

---

frontend/src/credits/components/CreditRequestDetailsPage.js

- recomend issuance modal--changed "recommend approval" to "recommend issuance"
- "issue credits" button disabled if comment is typed in
- removed "if recommended for issuance etc.." text from recommend page
- fixed issue credits button

credit request details page bugs/changes

---

frontend/src/app/css/Dashboard.scss
frontend/src/dashboard/DashboardContainer.js
frontend/src/dashboard/components/ActionsBceid.js
frontend/src/dashboard/components/ActionsIdir.js
frontend/src/dashboard/components/ActivityBanner.js
frontend/src/dashboard/components/Feedback.js

-added banner for vehicles in draft mode
-added links to no activity banners
-changed email address in feedback
-removed hover styling for no activity

bceid dashboard changes

---

frontend/src/credits/CreditRequestDetailsContainer.js
frontend/src/credits/UploadICBCVerificationContainer.js

added no data uploaded yet to previousUpload beginning state

icbc data current to: no data uploaded yet

---

backend/api/serializers/sales_submission.py
backend/api/serializers/sales_submission_content.py
frontend/src/credits/components/ModelListTable.js
frontend/src/sales/components/SalesSubmissionContentPage.js

Changelog:
- Fixed an issue with the VehicleMinSerializer throwing a 500 since request user isn't populated in some cases
- Changed how the detection works for sales so that it populates the warnings column
- Changed Warnings to Errors

ZEVA-252: Follow-up

---

frontend/src/app/components/Navbar.js

Changelog:
- Added an event listener and check where the element click is

Fixed the bug where clicking outside the navbar doesn't close the menu

---

frontend/src/app/components/AutocompleteInput.js
frontend/src/app/css/Autocomplete.scss
frontend/src/credits/components/CreditTransfersListPage.js
frontend/src/sales/components/SalesSubmissionPage.js
frontend/src/vehicles/VehicleEditContainer.js

Changelog:
- Fixed the suggested values for Autocomplete so that it doesn't push elements
- Added toUpperCase() on the suggested values so it doesn't list certain values more than once
- Changed how the buttons look like for certain pages so they're more consistent
- Some code cleanup

ZEVA-265: Autocomplete CSS fix

---

frontend/src/credits/CreditRequestDetailsContainer.js
frontend/src/credits/UploadICBCVerificationContainer.js

added condition for icbc upload date display so it says either the date or "no icbc data uploaded yet"

bug 8 -  icbc upload upload date display

---

frontend/src/app/components/Modal.js
frontend/src/app/components/StatusInterceptor.js
frontend/src/app/css/FileUpload.scss
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditTransfersPage.js
frontend/src/dashboard/components/UserSettings.js
frontend/src/organizations/components/AddressForm.js
frontend/src/sales/components/SalesUploadPage.js
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js

Changelog:
- Replace anything that uses h6 with h5
- Increased most of the h4 tags to h3
- Fixed upload layout for vehicle form
- Fixed missing comment for analysts

Follow-up Cleanup

---

backend/api/serializers/sales_submission.py
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/ModelListTable.js
frontend/src/credits/components/SalesSubmissionDetailsPage.js
frontend/src/credits/components/SubmissionListTable.js

Changelog:
- Sales and credits should now show up in the list page even if it's still in draft
- Should no longer show 0 sales in the details page
- Removed extra action bar in the Validate Vin table

ZEVA-246: Sales in the List Page

---

backend/api/serializers/sales_submission.py
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/ModelListTable.js

reordered columns
changed some column headers
removed warnings for records that have sales (checked)
disabled button if no warnings (but still shows up for bceid user for issued)

zeva 286 - credit application table

---

frontend/src/users/UserEditContainer.js
frontend/src/users/components/UserDetailsForm.js

Changelog:
- Removed the preventDefault for now

User Submit Fix

---

backend/api/serializers/sales_submission_content.py
backend/api/services/sales_spreadsheet.py
backend/api/viewsets/record_of_sale.py
frontend/src/app/css/App.scss
frontend/src/app/css/ReactTable.scss
frontend/src/app/router.js
frontend/src/app/routes/Credits.js
frontend/src/app/utilities/upload.js
frontend/src/credits/UploadICBCVerificationContainer.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/ModelListTable.js
frontend/src/sales/SalesSubmissionContainer.js
frontend/src/sales/components/SalesUploadPage.js

Changelog:
- Highlight the rows with invalid models as red
- Disable submit button if there are any invalid models
- Drafts are now editable

ZEVA-283: Prevent user from submitting drafts if there are invalid models for the submission

---

frontend/src/app/css/App.scss
frontend/src/credits/components/SalesSubmissionDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js

Changelog:
- Clear button in the validate page is now disabled, until filters are actually set
- Changed the css slightly so it's more obvious that the button is disabled
- Changed the condition for the modal text when submitting a zev model

Bug Fixes: 32, 33

---

frontend/.storybook/main.js
frontend/jest.config.js
frontend/package.json
frontend/src/app/components/Modal.js
frontend/src/credits/components/UploadVerificationData.js
frontend/src/credits/components/__tests__/UploadVerificationData.test.js
frontend/src/stories/__tests__/storyshots.test.js
frontend/src/vehicles/components/VehicleForm.js
frontend/src/vehicles/components/__tests__/VehicleForm.test.js

Changelog:
- Installed storyshots
- Minor changes to the tests to reduce the amount of warnings when running npm test

Storybook tests now included for coverage

---

backend/api/services/credit_transaction.py
frontend/src/app/components/FileDrop.js
frontend/src/app/css/Credits.scss
frontend/src/credits/UploadICBCVerificationContainer.js
frontend/src/credits/components/UploadVerificationData.js
frontend/src/vehicles/components/VehicleForm.js
frontend/src/vehicles/components/VehicleListTable.js

Changelog:
- Changed look so it's more consistent with the other pages
- Added alternating colour for background
- Added colour for icons
- More consistent spacing
- Fixed a bug with the account balance not getting the total value
- Updated credits in Vehicle List page so it contains two decimals always

Update ICBC Registration Data UI

---

backend/api/serializers/sales_submission.py
frontend/src/app/components/Alert.js
frontend/src/app/router.js
frontend/src/app/routes/Credits.js
frontend/src/credits/SalesSubmissionDetailsContainer.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/SubmissionListTable.js
frontend/src/stories/Alert.stories.js
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js

added alert type for credits, fixed moment formatting for date time, added more storybook tests for alerts

ZEVA 284 - status alerts

---

backend/api/models/sales_submission_content.py
backend/api/serializers/credit_transaction.py
backend/api/services/credit_transaction.py
frontend/src/app/components/Navbar.js
frontend/src/credits/components/CreditTransactionListTable.js
frontend/src/credits/components/CreditTransactions.js

Changelog:
- Transactions are now grouped together (regardless of model year, weight class and credit class)
- Added transaction Timestamp
- Reorganized the columns a bit

ZEVA-274: Grouped Transactions Together

---

frontend/src/app/components/Alert.js
frontend/src/app/css/Credits.scss
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/organizations/components/OrganizationDetailsPage.js

Changelog:
- Added a check for the history
- Minor css adjustments

Fallback check for the Alerts. Minor css adjustments

---

frontend/src/app/components/Alert.js
frontend/src/app/css/Dashboard.scss
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/dashboard/components/DashboardPage.js
frontend/src/organizations/components/OrganizationsTable.js

Changelog:
- Fixed the organizations table so it shows the credits
- Minor css changes

ZEVA-304: Credits in the Organizations Table

---

backend/api/models/sales_submission_content.py
backend/api/services/sales_spreadsheet.py
frontend/src/app/constants/errorCodes.js
frontend/src/app/css/ReactTable.scss
frontend/src/credits/components/CreditRequestVINListPage.js
frontend/src/credits/components/VINListTable.js

Changelog:
- Updated the description of error codes
- Updated how the warnings and critical errors are highlighted

ZEVA-295: Updated Error Codes

---

backend/api/fixtures/operational/0011_add_model_year_2021.py

ZEVA 307 : add MY 2021

---

frontend/src/credits/CreditTransfersContainer.js
frontend/src/credits/components/CreditTransfersPage.js

edited save function and form fields so that only credit seller can initiate transfer
-removed radio buttons
-hard coded debit from variable in save function in container

ZEVA 301- Change - only credit seller allowed to intitiaite transfer

---

frontend/src/vehicles/components/VehicleDetailsPage.js

Changelog:
- Added checks on the front-end for the zev detail page so it doesn't show the validate functions don't show if you don't have permissions to update it

Added check for the validate and reject functions to show up

---

frontend/src/app/css/Dashboard.scss

Changelog:
- Words should now break a bit more gracefully
- Improved spacing all over the dashboard

Improved spacing around the dashboard

---

frontend/src/app/css/Dashboard.scss
frontend/src/dashboard/DashboardContainer.js
frontend/src/dashboard/components/ActionsBceid.js

-added rejected models and transfers activity banners for bceid

ZEVA 282 - new activity banners for bceid

---

frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/credits/components/CreditTransfersPage.js
frontend/src/credits/components/CreditTransfersSignOff.js
frontend/src/dashboard/components/ActionsIdir.js

-transfer draft can now be submitted to trade partner
-trade partner can check off boxes
-dashboard (idir) analyst acton bar (credits) now has two filter words (validated, submitted)

Bugs fixes - transfer submit draft, checkboxes enabled, dashboard filter action bar

---

frontend/src/app/components/Alert.js
frontend/src/app/components/__tests__/ErrorHandler.test.js
frontend/src/app/components/__tests__/Footer.test.js
frontend/src/app/utilities/__tests__/formatNumeric.test.js
frontend/src/app/utilities/formatNumeric.js
frontend/src/credits/CreditRequestDetailsContainer.js
frontend/src/credits/CreditTransfersDetailsContainer.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/credits/components/__tests__/CreditTransfersDetailsPage.test.js

- fixed action bar in transfer details
- added tests
-alert now says "icbc date current to: no icbc data" if no icbc data uploaded, otherwise it will have the date

Friday testing

---

backend/api/viewsets/icbc_verification.py

Changelog:
- Moved files being uploaded to /zeva-uploads/

Explicitly specified which folder to upload to

---

backend/api/viewsets/icbc_verification.py

Changelog:
- instead of /zeva-upload/ we're just using tmp

Change directory to tmp

---

backend/api/viewsets/icbc_verification.py

Changelog:
- Temporarily removed automatic file deletion
- Changed folder back to the way it was

Upload directory back from tmp

---

backend/api/viewsets/icbc_verification.py
frontend/src/credits/UploadICBCVerificationContainer.js

Changelog:
- Moved the upload message in finally
- Restored delete functionality

Upload Changes

---

backend/api/tests/test_credit_transfers.py
backend/api/viewsets/credit_transfer.py
frontend/src/app/components/Button.js
frontend/src/credits/components/CreditTransfersDetailsActionBar.js
frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/credits/components/__tests__/CreditTransfersDetailsPage.test.js

fixed frontend tests and added backend tests for transfers

November 13 testing

---

backend/api/models/vehicle.py

Changelog:
- Explicit conditions for showing credit class C
- Explicit conditions for showing credit class A

ZEVA-335: Update Get Credit Class

---

backend/api/management/commands/load_ops_data.py

Changelog:
- Added sort() to ensure the order of the scripts
- Removed unused functions

Operational Scripts Order

---

backend/api/serializers/sales_submission.py
frontend/src/credits/components/CreditRequestListTable.js

updated date field in sales submission to show submission date if the current status is government-altered ie recommended or checked and the user is BCEID

ZEVA 342 - sales submission list table date field - use history table to grab submission date

---

frontend/src/app/PageLayout.js
frontend/src/app/components/Disclaimer.js
frontend/src/app/css/App.scss
frontend/src/app/css/Footer.scss
frontend/src/app/css/index.scss

added disclaimer text for bceid users

ZEVA 339 - Disclaimer text

---

backend/api/fixtures/test/0005_add_bceid_user_roles.py

Changelog
- To fix the error that's showing up when running the test fixtures

Fixed test fixtures

---

backend/api/serializers/credit_transfer.py
backend/api/services/credit_transaction.py
backend/api/viewsets/credit_transfer.py
frontend/src/credits/CreditTransfersDetailsContainer.js
frontend/src/credits/CreditTransfersEditContainer.js
frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/credits/components/CreditTransfersForm.js
package-lock.json

added more backend checks for transfers
-analyst will see a banner if this transfer will put supplier into negative (including pending)
-supplier cannot submit transfers that will put them into negative (including pending)
-director cannot issue credits if supplier does not have enough credits (backend only)

ZEVA-356: Transfer error

---

frontend/src/app/components/Alert.js
frontend/src/credits/UploadCreditRequestContainer.js
frontend/src/credits/components/CreditRequestsUploadPage.js
frontend/src/credits/components/UploadVerificationData.js

-added axios call to retrieve icbc upload date and replaced hard coded date with that response
-added alert class for icbc data so correct alert is now showing after upload

ZEVA 354 - icbc date

---

frontend/src/dashboard/components/ActionsIdir.js
frontend/src/vehicles/components/VehicleListTable.js

Changelog:
- Changed Approved filter to Recommend for Credit Transfers (from dashboard)
- Changed Zev Class to ZEV Class

ZEVA-357: Credit Transfer Dashboard fix

---

frontend/src/organizations/components/UsersTable.js

Changelog:
- Added sorting of the roles

ZEVA-361: Roles sorting

---

frontend/src/app/components/Navbar.js

Changelog:
- Added a check to credit transactions (now checks for view sales)

ZEVA-362: Permission check for Credit Transaction Tab

---

backend/api/fixtures/operational/0015_add_credit_transfer_permissions.py
backend/api/serializers/credit_transfer.py
frontend/src/dashboard/DashboardContainer.js
frontend/src/dashboard/components/ActionsIdir.js

Changelog:
- Added some checks to the axios calls in the dashboard
- New fixture to add some permissions to bceid roles
- When signing, it should now properly track on who signed the credit transfer

ZEVA-363: Fix Permission Checks for Admin

---

frontend/src/app/utilities/getCreditRequestSummary.js

Changelog:
- Changed the count so it that it's not using the aggregate sales

Fixed credit request summary calculation

---

frontend/src/credits/UploadCreditRequestContainer.js

Removed duplicate loading

---

backend/api/viewsets/credit_transfer.py

added disapproved status to transfer list for bceid --so they can see anything that has been rejected by partner or them

added "disapproved" to filter list for bceid transfer viewset

---

backend/api/serializers/credit_transfer.py
frontend/src/credits/components/CreditRequestVINListPage.js

Changelog:
- Used calculate_insufficient_credits function so it includes credit applications as well

Fixed an issue with credit calculation

---

backend/api/viewsets/credit_request.py

Changelog:
- Added conditions to check where there is 0 record of sale or when the sale submission is submitted. If so, unselected vins are based on content that have certain warnings.

Fixed a bug where nothing is automatically selected anymore

---

backend/api/permissions/credit_request.py
backend/api/permissions/credit_transfer.py
backend/api/serializers/credit_transfer.py

Changelog:
- misunderstood how the permission check should work. So fixed this
- Fixed calculate insufficient credits caused by bad merge

Fixed permission errors

---

frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditRequestsPage.js
frontend/src/credits/components/CreditTransfersListPage.js

Changelog:
- I forgot to add a typeof check

Front-end Permission check fix

---

backend/api/fixtures/test/0000_add_users.py

Changelog:
- Added Navpreet to the list of users
- Added emails and keycloak emails

Update User Fixtures

---

backend/api/serializers/credit_transfer.py
backend/api/services/credit_transaction.py
frontend/src/app/components/Alert.js
frontend/src/app/components/Comment.js
frontend/src/credits/CreditTransfersDetailsContainer.js
frontend/src/credits/CreditTransfersEditContainer.js
frontend/src/credits/components/CreditRequestAlert.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditTransfersAlert.js
frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/credits/components/CreditTransfersForm.js
frontend/src/credits/components/CreditTransfersListTable.js
frontend/src/credits/components/UploadVerificationData.js
frontend/src/credits/components/__tests__/CreditTransfersDetailsPage.test.js
frontend/src/stories/CreditRequestAlert.stories.js
frontend/src/stories/VehicleAlert.stories.js
frontend/src/vehicles/components/VehicleAlert.js
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js

-split alerts so that each feature has its own file to do the logic and call the basic alert component, updated all features with alerts
-made comment component use more shallow comment array
-added all transfer status alerts

ZEVA 347 - Credit transfer status alerts

---

frontend/src/dashboard/components/Feedback.js

updated email address on dashboard from CEVinquiries to ZEVRegulations

ZEVA 388  - new email address

---

backend/api/serializers/sales_submission.py
backend/api/viewsets/credit_request.py
frontend/src/credits/CreditRequestDetailsContainer.js
frontend/src/credits/CreditRequestVINListContainer.js
frontend/src/credits/CreditTransfersDetailsContainer.js
frontend/src/credits/components/CreditRequestAlert.js
frontend/src/credits/components/CreditRequestDetailsPage.js

Changelog:
- Added an exclude filter for statuses irrelevant for non-government users
- Added a modal confirm dialog to reset the list of selected vins if the icbc data got updated

ZEVA-369: Fixed Name Associated with the Status History 

---

frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js

Changelog:
- Changed the labels for the vehicle details page to match the one in the listing page
- Updated the header for the upload test range results

ZEVA-393, 399, 400: Label Changes

---

frontend/src/app/components/VehicleSupplierTabs.js
frontend/src/dashboard/components/Administration.js
frontend/src/organizations/VehicleSupplierCreditTransactionListContainer.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/organizations/VehicleSupplierModelListContainer.js
frontend/src/organizations/VehicleSupplierUserListContainer.js

changes link on dashboard in administration section
adds user prop to supplier tabs and checks permissions before showing tabs

ZEVA 391 -  idir admin only role

---

frontend/src/app/components/Navbar.js
frontend/src/dashboard/components/ActionsBceid.js
frontend/src/dashboard/components/DashboardPage.js

removed navbar link and activity section from bceid users that dont have permissions for sales and transfers

ZEVA 395 - BCEID admin only role

---

frontend/src/app/components/FileDrop.js
frontend/src/credits/UploadCreditRequestContainer.js
frontend/src/credits/components/CreditRequestsUploadPage.js

Changelog:
- Selecting a different file clears the error message
- Removing the file clears the error message

ZEVA-401: Automatically Clear Error Message

---

frontend/src/app/components/Navbar.js

added condition for displaying credit transaction tab in navbar to idir users

credit transaction tab on navbar

---

frontend/src/credits/components/CreditTransfersForm.js

fixed condition for showing button on transfer modal

testing bugs

---

backend/api/management/commands/generate_initial_notification_settings.py
backend/api/serializers/notification.py
backend/api/serializers/user.py
backend/api/services/user.py
backend/api/viewsets/notification.py
frontend/src/notifications/NotificationListContainer.js

Changelog:
- Service function to populate the user notification subscription
- Command to populate notification subscriptions for existing users
- Automatically select all notifications for new users

Populate Notification Subscriptions for Existing Users

---

frontend/src/dashboard/DashboardContainer.js
frontend/src/dashboard/components/ActionsIdir.js

Changelog:
- Fixed the banner showing awaiting director approval when it should be waiting for analyst

Dashboard Banner for Credit Transfer

---

frontend/src/credits/components/CreditTransfersDetailsTable.js

fixes rounding on transfer details table

transfer details table credit quantity ceil to formatNumeric

---

backend/api/serializers/credit_transfer.py
backend/api/serializers/sales_submission.py
frontend/src/credits/components/CreditRequestListTable.js
frontend/src/credits/components/CreditTransfersListTable.js
frontend/src/dashboard/DashboardContainer.js

Changelog:
- Added updated_timestamp to serializer
- Check so that updatedTimestamp is validated against 28 days from today
- Changed sorting to updatedTimestamp descending

ZEVA-406: Dashboard now limits the finalized activities from 28 days to current date

---

backend/api/services/send_email.py
backend/api/viewsets/credit_transfer.py

-Moved send email logic for transfer to "send_email.py"
- added filters to send email only to interested organizations.
- Exclude the user who is taking action on the item.

Notification fix

---

backend/api/viewsets/credit_transfer.py

Changelog:
- Restored the check and call to validate_transfer

Issue Credits Fix for Credit Transfer

---

frontend/src/vehicles/VehicleEditContainer.js
frontend/src/vehicles/components/VehicleDetailsPage.js

submitting/saving vehicle draft redirects to details page
new button to submit draft from details page

ZEVA 394 - Vehicle workflow

---

frontend/src/app/components/Navbar.js
frontend/src/app/config.js
frontend/src/app/config/features.js
frontend/src/app/css/Navbar.scss

Changelog:
- Removed old commented out code
- Added notifications as part of the features.js

ZEVA-414: Notifications can now be hidden via front-end configuration

---

frontend/src/vehicles/VehicleDetailsContainer.js
frontend/src/vehicles/VehicleEditContainer.js
frontend/src/vehicles/components/VehicleDetailsPage.js

fixes redirects for saving draft and submitting from details page

ZEVA 394: Vehicle workflow redirect

---

frontend/src/vehicles/VehicleDetailsContainer.js

Changelog:
- Fixed the reload by pushing a route to list then replacing it

Vehicle Details Reload

---

frontend/src/credits/components/CreditTransactionListTable.js
frontend/src/credits/components/CreditTransactions.js
frontend/src/credits/components/CreditTransfersDetailsSupplierTable.js

Changelog:
- Fixed the unending decimals issue in the transfer details page
- Fixed transfers and sales submission getting merged together in credit transactions page if they have the same id

Transaction Page fixes

---

backend/api/serializers/credit_transfer.py
backend/requirements.txt
frontend/package-lock.json
frontend/package.json
frontend/src/app/components/Comment.js
frontend/src/dashboard/components/ActionsBceid.js

Changelog:
- Fixed filtering recorded transfers from the dashboard
- Updated packages as recommended by dependabot

ZEVA-372, 410: Fixed filtering for recorded transfers

---

frontend/src/credits/components/CreditRequestListTable.js

Changelog:
- Changed the column name to Total Eligible Sales

ZEVA-419: Changed column name to Total Eligible Sales

---

backend/api/fixtures/operational/0018_update_notifications.py
backend/api/serializers/credit_transfer.py
backend/api/serializers/vehicle.py
backend/api/services/send_email.py
backend/api/viewsets/notification.py
frontend/src/notifications/NotificationListContainer.js

ZEVA-382, 377:Added email notification setup for ZEV Model 
ZEVA-408: Email notification page changes

ZEVA: 408, 382, 377

---

backend/api/viewsets/credit_request.py
frontend/src/credits/components/CreditRequestVINListPage.js
frontend/src/credits/components/VINListTable.js
frontend/src/vehicles/components/VehicleListTable.js

Changelog:
- Added dropdown filter for the VINs
- Fixed some filtering issues

ZEVA 403: Added dropdown filter

---

backend/api/viewsets/organization.py
frontend/src/app/routes/Organizations.js
frontend/src/credits/components/CreditTransactions.js
frontend/src/organizations/VehicleSupplierCreditTransactionListContainer.js
frontend/src/organizations/components/VehicleSupplierSalesListPage.js

ZEVA-423: IDIR - not seeing all supplier transactions

---

frontend/src/credits/components/CreditRequestAlert.js
frontend/src/credits/components/CreditRequestDetailsPage.js

Changelog:
- Should now show date current to when it was checked, not the current icbc date

ZEVA-420: ICBC Date Fix

---

frontend/src/app/components/Comment.js
frontend/src/credits/CreditTransfersEditContainer.js
frontend/src/credits/components/CreditTransfersForm.js

Changelog:
- Added delete function for rescinded status

ZEVA-405: Added delete function for rescinded

---

backend/api/permissions/upload.py
backend/api/permissions/vehicle.py
backend/api/services/minio.py
backend/api/urls.py
backend/api/viewsets/icbc_verification.py
backend/api/viewsets/upload.py
frontend/src/app/css/Credits.scss
frontend/src/app/routes/Uploads.js
frontend/src/credits/UploadICBCVerificationContainer.js
frontend/src/credits/components/UploadVerificationData.js

Changelog:
- Added permission check
- Changed upload icbc to use minio
- Automatically download the icbc data from minio into the system
- Added vehicle permission (currently unused)

ZEVA-430: Changed upload icbc so it uses minio

---

backend/api/serializers/sales_submission.py
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/ModelListTable.js

Changelog:
- Removed Warnings
- Removed Total Credits
- Renamed Sales to Sales Submitted
- Added Eligible Sales
- Added Eligible ZEV Credits
- Merged Model Year, Make and Model

ZEVA-427: Credit Application Table Changes

---

frontend/src/app/components/ComplianceTabs.js
frontend/src/app/components/Navbar.js
frontend/src/app/router.js
frontend/src/app/routes/Compliance.js
frontend/src/app/routes/CreditTransfers.js
frontend/src/compliance/ComplianceCalculatorContainer.js
frontend/src/compliance/components/ComplianceCalculatorDetailsPage.js

Changelog:
- Add route for Edit Compliance Report
- Add route for Add Compliance Report
- Add route for Compliance Calculator
- Fixed highlighting for the navbar

ZEVA-431: Updated Routes for Compliance Report

---

frontend/src/app/css/App.scss
frontend/src/app/css/ComplianceReportTabs.scss
frontend/src/app/css/index.scss
frontend/src/app/routes/Compliance.js
frontend/src/compliance/ComplianceReportsContainer.js
frontend/src/compliance/components/ComplianceReportTabs.js

Changelog:
- Created ComplianceReportTabs component
- Updated css

ZEVA-438: Compliance Report Tabs

---

backend/api/serializers/sales_submission.py
backend/api/viewsets/credit_request.py
frontend/src/app/components/FileDropArea.js
frontend/src/app/components/FileDropEvidence.js
frontend/src/credits/UploadCreditRequestContainer.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditRequestsUploadPage.js
frontend/src/users/components/UserDetailsForm.js

-adds checkbox to excel file upload to display or not (optional and will not throw errors if no file is selected
-adds excel file name so user knows what is already there
-adds ability to delete evidence or add new
-adds text for file types and max number for evidence

ZEVA 426 - evidence reupload options, deleting, and text on file types/numbers

---

frontend/src/app/css/ComplianceReport.scss
frontend/src/app/css/index.scss
frontend/src/app/router.js
frontend/src/compliance/SupplierInformationContainer.js
frontend/src/compliance/components/ComplianceReportAlert.js
frontend/src/compliance/components/ComplianceReportTabs.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js
frontend/src/dashboard/components/Feedback.js

Changelog:
- Made it accessible through /compliance/reports/new/supplier-information
- Added ComplianceReportAlert
- List of Makes is editable
- Current list of makes are read from the vehicle table

ZEVA-433, 441: Supplier Information

---

frontend/src/app/router.js
frontend/src/compliance/CreditActivityContainer.js
frontend/src/compliance/components/CreditActivityDetailsPage.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js
frontend/src/credits/components/CreditBalanceTable.js
frontend/src/credits/components/CreditTransactionListTable.js
frontend/src/credits/components/CreditTransactions.js

Changelog:
- Created Credit Activity Container
- Renamed SupplerInformation class name
- Moved balance table logic into the component
- Moved credit transaction logic into the component

ZEVA-435: Credit Activity

---

frontend/src/credits/components/CreditRequestAlert.js
frontend/src/credits/components/CreditRequestListTable.js
frontend/src/credits/components/CreditTransfersAlert.js
frontend/src/credits/components/CreditTransfersListTable.js

adds id to alerts and list tables for credit transfers and applications

ZEVA 444 - Ids CA and CT to alerts and tables

---

backend/api/tests/test_credit_transfers.py
frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/credits/components/__tests__/CreditTransfersDetailsPage.test.js
frontend/src/credits/components/__tests__/SalesListTable.test.js
frontend/src/notifications/components/NotificationListPage.js
frontend/src/notifications/components/__tests__/NotificationList.test.js
frontend/src/stories/DashboardPage.stories.js
frontend/src/vehicles/components/__tests__/ActionBarNonGov.test.js

Changelog:
- Just some fixes for the unit tests for frontend and backend

Fixed unit tests

---

backend/api/services/sales_spreadsheet.py

Changelog:
- Increased the width for Vehicle Model, VIN, sales date and errors column for the spreadsheets

ZEVA-328: Increased the width for the spreadsheets

---

frontend/src/credits/UploadCreditRequestContainer.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditRequestsUploadPage.js

-makes upload new excel default checked for draft but checks for files.length before attempting upload
-changes button text for re-uploading files

ZEVA-456 - re-upload files for credit application

---

frontend/src/credits/CreditTransfersDetailsContainer.js
frontend/src/credits/CreditTransfersEditContainer.js

If status is DRAFT, RESCIND, redirect user to edit page else reload the detail page to update the status alert.

ZEVA-464:Credit transfer pages - staying on transfer detail page after save/submit/rescind/recommend//reject/record

---

backend/api/serializers/model_year_report.py
frontend/src/compliance/SupplierInformationContainer.js

Changelog:
- Address is now saved when creating a new model year report

ZEVA-449: Model Year Report Address

---

frontend/src/vehicles/components/VehicleDetailsPage.js

- changes text in modal for making zev models inactive

make vehicle inactive text change

---

frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/credits/components/CreditTransfersDetailsTable.js
frontend/src/credits/components/CreditTransfersForm.js
frontend/src/vehicles/components/VehicleListTable.js

Changelog:
- Added commas to values for Credit Transfer
- Draft ZEVs no longer show active status

ZEVA-470, 483: ZEV and Credit Transfer Tweaks

---

frontend/src/app/css/App.scss
frontend/src/app/css/ComplianceReport.scss
frontend/src/app/router.js
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/components/ComplianceObligationDetailsPage.js
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
frontend/src/compliance/components/ComplianceReportSignOff.js
frontend/src/compliance/components/ComplianceReportTabs.js

-adds page for compliance obligation
-all values are hardcoded so will need to be revisited when backend is finished

ZEVA-460 : Compliance Obligation page

---

frontend/src/notifications/components/NotificationListPage.js

Changelog:
- Reapply the fix lost due to merge conflict resolution

Reapply Navpreet's fix for notifications

---

frontend/src/app/css/App.scss
frontend/src/app/css/Credits.scss
frontend/src/credits/components/AnalystRecommendationHeader.js
frontend/src/credits/components/CreditApplicationHeader.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/ModelListTable.js
frontend/src/credits/components/getAnalystRecommendationColumns.js

Changelog:
- Analyst Recommendation Columns
- Analyst Recommendation Header
- Footer for the totals
- Logic to show/hide certain columns depending on the user logged in.

ZEVA-465: Analyst Recommendation Columns

---

frontend/src/app/css/ComplianceReportSummary.scss
frontend/src/app/css/index.scss
frontend/src/app/router.js
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js
frontend/src/compliance/components/SummaryConsumerSalesTable.js
frontend/src/compliance/components/SummaryCreditActivityTable.js
frontend/src/compliance/components/SummarySupplierInfo.js

shows tables with supplier information, credit activity, and consumer sales information.
frontend only so values are hardcoded

ZEVA 436 - Summary Page (frontend)

---

backend/api/services/sales_spreadsheet.py

Changelog:
- Added an initial check if the row has a reason and output that to the spreadsheet

Added the manually selected reason to the download errors

---

backend/api/fixtures/operational/0024_update_roles_permissions.py
backend/api/fixtures/operational/0025_update_notifications.py
frontend/src/users/components/UserDetailsForm.js

- Added fixtures to add new permission and also update role_permissions.
- Updated notifications for BCeID user.
- Added notification email to user form.

ZEVA-488,510: email Notification configuration bceid signing authority

---

backend/api/serializers/model_year_report.py
backend/api/viewsets/model_year_report_consumer_sales.py
frontend/src/app/PageLayout.js
frontend/src/app/components/Disclaimer.js
frontend/src/app/router.js
frontend/src/app/routes/Compliance.js
frontend/src/compliance/ComplianceReportsContainer.js
frontend/src/compliance/ConsumerSalesContainer.js
frontend/src/compliance/SupplierInformationContainer.js
frontend/src/compliance/components/ComplianceReportListPage.js
frontend/src/compliance/components/ComplianceReportsTable.js
frontend/src/compliance/components/ConsumerSalesDetailsPage.js

- Updated disclaimer.
- Removed static values for report list.
- Updated routes.
- Other minor changes

ZEVA-493:Model Year report listing page (backend)

---

backend/api/serializers/sales_submission.py

Changelog:
- Changed the condition for displaying the "balance" in the listing page

ZEVA-509: Fixed Incorrect Credit Balance

---

backend/api/services/icbc_upload.py
frontend/src/credits/components/CreditRequestValidatedDetailsPage.js

Changelog:
- Added conditions so in case electric is flagged as False, then it checks the fuel type if it's hybrid/electric

ICBC upload now checks the fuel type if its electric or hybrid

---

frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/credits/components/CreditTransfersSignOff.js

-fixes bug so that tooltip shows for transfer buyer if they do not have permission to check boxes
-lints page

transfer checkboxes buyer without permission tooltip bug

---

backend/api/fixtures/operational/0026_update_notifications.py

- Added new fixture to update the permission for ZEV Model notifications.

Changed permission for Zev Model notifications. Only zev_user will be able to see zev Model notifications.

---

backend/api/models/credit_transfer_history.py
frontend/src/credits/components/AnalystRecommendationHeader.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/ModelListTable.js
frontend/src/credits/components/VINListTable.js

Changelog:
- Blank option for Reason
- Analyst Recommendation text condition
- Added text for director

ZEVA-520: Credit Application Workflow Changes

---

backend/api/services/icbc_upload.py

Changelog:
- changed so that we update the model_id if it doesn't match with the new upload

Change to automatically update the icbc vehicle date if it's different

---

backend/api/services/icbc_upload.py

Changelog:
- Update the model and upload date as needed

Changed code to update_or_create so it updates the models when there are changes from the csv

---

backend/api/serializers/model_year_report.py
backend/api/serializers/model_year_report_address.py
backend/api/serializers/model_year_report_history.py
backend/api/serializers/model_year_report_make.py
backend/api/viewsets/model_year_report.py
frontend/src/compliance/ComplianceReportsContainer.js
frontend/src/compliance/SupplierInformationContainer.js
frontend/src/compliance/components/ComplianceReportAlert.js
frontend/src/compliance/components/ComplianceReportSignOff.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js

Changelog:
- Loading from snapshot if confirmed, otherwise load from current data
- Clicking on save should now update the record instead of creating a new one

ZEVA-519: Model Year Report Load from Snapshot

---

frontend/src/app/config.js
frontend/src/app/config/features.js
frontend/src/app/css/ComplianceReport.scss
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/ComplianceReportsContainer.js
frontend/src/compliance/ConsumerSalesContainer.js
frontend/src/compliance/SupplierInformationContainer.js
frontend/src/compliance/components/ComplianceReportListPage.js
frontend/src/compliance/components/ConsumerSalesDetailsPage.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js

Changelog:
- Added dropdown beside new button for the years
- Removed hardcoded year for supplier information and consumer sales
- Moved some calls around for Credit Obligation so it won't result into a timing issue
- ESLint Fixes

ZEVA-494: Model Year Report Dropdown

---

backend/api/serializers/icbc_upload_date.py
frontend/src/credits/CreditRequestDetailsContainer.js
frontend/src/credits/components/CreditRequestDetailsPage.js

Changelog:
- Instead of upload date, we're not detecting changes based on update timestamp (ie if upload date timestamp > than application timestamp

ZEVA-531: Changed how the detection works slightly

---

backend/api/serializers/model_year_report.py
frontend/src/compliance/SupplierInformationContainer.js
frontend/src/compliance/components/ComplianceReportSignOff.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js
frontend/src/credits/CreditTransfersDetailsContainer.js

Changelog:
- Added Edit button
- Modal to reset the confirmation
- Prevent duplicates of confirmations

ZEVA-508: Allow users to reset their confirmations

---

backend/api/models/model_year_report_statuses.py
backend/api/serializers/model_year_report.py
backend/api/viewsets/model_year_report.py
backend/api/viewsets/model_year_report_consumer_sales.py
frontend/src/app/routes/Compliance.js
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/components/ComplianceReportListPage.js
frontend/src/compliance/components/ComplianceReportTabs.js
frontend/src/compliance/components/ComplianceReportsTable.js

-Added new statuses.
-Added endpoint to update the status of the report when user click submit.
-Filter report list based on BCEID/IDIR users.

ZEVA-496, 528: Update validation status of report and Model year report index page for IDIR user.

---

backend/api/serializers/model_year_report.py
backend/api/services/model_year_report.py
backend/api/viewsets/model_year_report.py
frontend/src/app/components/VehicleSupplierTabs.js
frontend/src/app/css/ComplianceReport.scss
frontend/src/app/css/ComplianceReportTabs.scss
frontend/src/app/router.js
frontend/src/app/routes/Organizations.js
frontend/src/compliance/ComplianceReportsContainer.js
frontend/src/compliance/SupplierInformationContainer.js
frontend/src/compliance/components/ComplianceReportAlert.js
frontend/src/compliance/components/ComplianceReportListPage.js
frontend/src/compliance/components/ComplianceReportsTable.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js
frontend/src/organizations/VehicleSupplierReportListContainer.js
frontend/src/organizations/VehicleSupplierUserListContainer.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js

Changelog:
- Added a report tab for Suppliers
- Allowed suppliers to click on the report and view them

ZEVA 532: Report Tab for Suppliers

---

frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/components/ComplianceObligationDetailsPage.js

Created a function to perform credit reduction calculation.
- if supplier is large, perform ZEV Class A reduction and assign new balance else initial balance will stay same for both the years.
- If A selected, perform older year A reduction -> older year B reduction -> current year A reduction -> current year B reduction,  for unspecified Credit Reduction
- If B selected, perform older year B reduction -> older year A reduction -> current year B reduction -> current year A reduction,  for unspecified Credit Reduction.

ZEVA-501: Compliance Obligation - Determine logic for restrictions on credit offset

---

backend/api/serializers/model_year_report_compliance_obligation.py
backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/compliance/ComplianceObligationContainer.js

-deletes old obligation snapshots before creating new ones
-loads and saves confirmations for obligation

Compliance obligation cleanup

---

backend/api/serializers/credit_transaction.py
backend/api/services/summary.py
backend/api/viewsets/model_year_report_compliance_obligation.py

Changelog:
- Moved the logic from the serializer to the viewset temporarily so the data matches how its parsing the snapshot

Summary Fix

---

backend/api/serializers/model_year_report.py
frontend/src/app/css/ComplianceReportTabs.scss
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/ConsumerSalesContainer.js
frontend/src/compliance/SupplierInformationContainer.js
frontend/src/compliance/components/ComplianceObligationDetailsPage.js
frontend/src/compliance/components/ComplianceReportTabs.js
frontend/src/compliance/components/ConsumerSalesDetailsPage.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js

Changelog:
- Added edit buttons to Consumer Sales and Compliance Obligation
- Automatic refresh to update the status

Added Missing Next and Edit buttons

---

frontend/src/compliance/ConsumerSalesContainer.js

Changelog:
- Just removing the extra import

Removed duplicate history

---

frontend/src/compliance/ConsumerSalesContainer.js

Changelog:
- Placed the get statuses as part of axios all

Fixed timing issue for statuses

---

backend/api/models/credit_transaction.py
backend/api/services/summary.py

Changelog:
- Fixed an issue where the data is throwing off a 500 error
- Refactored a bit so the code is more readable

Parse Serializer Bug FIx

---

backend/api/serializers/sales_submission.py
backend/api/viewsets/credit_request.py

Changelog:
- Added another condition to parse date strings instead of xls specific dates

Fixing a date issue if the xls contains date strings

---

backend/api/serializers/sales_submission.py
backend/api/viewsets/credit_request.py

Changelog:
- Applying the same fix as #668

Applying PR668 to current DEV

---

backend/api/serializers/model_year_report_compliance_obligation.py
backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/components/ComplianceObligationAmountsTable.js

-grabs offset values from backend and stores in offsetValues state

ZEVA-551 - Offset values

---

backend/api/viewsets/model_year_report.py
frontend/src/app/css/ComplianceReportSummary.scss
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/components/ComplianceReportSignOff.js
frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js
frontend/src/compliance/components/SummaryCreditActivityTable.js

-- Summary page credit obligation related front end changes
-- Checkbox changes on summary page( frontend and backend)

ZEVA-540: bceid MYR Summary front end changes, 504:Summary page - capture the signing confirmation

---

frontend/src/credits/CreditRequestVINListContainer.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditRequestVINListPage.js
frontend/src/credits/components/VINListTable.js

Changelog:
- Removed modal logic
- Added another button to Re-verify with ICBC data explicitly
- Added logic with the reasons so it clears it properly

ZEVA-538: Updated Credit Application Review

---

frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/components/ComplianceObligationAmountsTable.js
frontend/src/compliance/components/ComplianceObligationDetailsPage.js
frontend/src/compliance/components/ComplianceObligationReductionOffsetTable.js
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js

--Offset logic change
--some UI changes

ZEVA-550:Integrate Offset Logic to Compliance Obligation

---

backend/api/services/model_year_report.py
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/ConsumerSalesContainer.js
frontend/src/compliance/components/ComplianceReportAlert.js
frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js

Changelog:
- Added Status for Summary Page
- Added progress bar status for Summary

ZEVA 547: Summary Page Status and Progress Bar

---

backend/api/fixtures/operational/0028_update_model_year.py

Changelog:
- Changed to update_or_create

Minor Fixture Update

---

backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/ConsumerSalesContainer.js
frontend/src/compliance/components/SummaryCreditActivityTable.js

-adds provisional BEFORE offset and provisional AFTER offset variables (before includes pending, after is that plus offset)
-fixes an issue with years for ratios comparing string to int

zeva 565 Summary offset and provisional numbers

---

backend/api/services/model_year_report.py
backend/api/viewsets/model_year_report.py
frontend/src/app/css/ComplianceReport.scss
frontend/src/app/router.js
frontend/src/compliance/AssessmentContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/ComplianceObligationAmountsTable.js
frontend/src/compliance/components/ComplianceReportAlert.js
frontend/src/compliance/components/ComplianceReportTabs.js
frontend/src/compliance/components/TableSection.js

-still needs work
-basic assessment page that displays transactions, has comment boxes, obligation numbers
-needs more logic for the offset area
-needs permissions for the page

ZEVA 542 - IDIR assessment page

---

backend/api/services/summary.py
backend/api/viewsets/model_year_report_compliance_obligation.py

- Created a function to calculate prior year balance
** pending: current year balances calculation needs more discussion.

ZEVA-563: Add function for retrieving obligation balances broken down  by year

---

frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js
frontend/src/compliance/components/SummaryConsumerSalesTable.js
frontend/src/compliance/components/SummaryCreditActivityTable.js
frontend/src/compliance/components/SummarySupplierInfo.js

* removed ldvSales and avgSale info from consumerSales 
* Added ldvSales to compliance obligation 
* Added avg and supplier class to supplier info

Summary page updates

---

backend/api/models/organization.py
backend/api/serializers/organization.py
backend/api/viewsets/model_year_report.py
frontend/src/app/routes/Compliance.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/organizations/components/VehicleSupplierClass.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js

Changelog:
- new property to check if the organization has submitted a report
- Code cleanup and some formatting
- New route to get years for model year reports

ZEVA-581: Minor clean up

---

frontend/src/app/css/ComplianceReport.scss
frontend/src/app/router.js
frontend/src/app/routes/Compliance.js
frontend/src/compliance/AssessmentEditContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/AssessmentEditPage.js
frontend/src/compliance/components/AssessmentSupplierInformationMakes.js

- Created new edit container and edit page  for assessment editing.
- created new route Edit for assessment

ZEVA-559: Initial commit for assessment edit makes feature.

---

backend/api/models/model_year_report.py
backend/api/serializers/model_year_report.py
frontend/src/app/utilities/getClassAReduction.js
frontend/src/app/utilities/getTotalReduction.js
frontend/src/app/utilities/getUnspecifiedClassReduction.js
frontend/src/compliance/AssessmentContainer.js
frontend/src/compliance/AssessmentEditContainer.js
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/AssessmentEditPage.js
frontend/src/compliance/components/ConsumerLDVSales.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js

Changelog:
- Added LDV Sales frontend
- Created utility functions to get the reductions to simplify the code

ZEVA-558: Consumer Sales Edit Frontend

---

frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/components/ComplianceObligationAmountsTable.js
frontend/src/compliance/components/ComplianceObligationDetailsPage.js

Changelog:
- Frontend to add the consumer sales input into Compliance Obligation

ZEVA-576: Frontend section for the Consumer Sales section in Compliance Obligation

---

backend/api/serializers/model_year_report.py

-filters by 3 prior years on backend for confirmed MY reports

Model year report supplier information 3 previous years fix

---

backend/api/models/organization.py
backend/api/serializers/organization.py
backend/api/viewsets/organization.py
frontend/src/organizations/VehicleSupplierDetailsContainer.js

Changelog:
- Added order_by statements to ldv_sales calls
- Code clean up

ZEVA-591: LDV Sales Sorting

---

backend/api/models/organization.py

Changelog:
- Reverted how the average is being called as it was adding confusion

ZEVA-591: Adjusted how credit average sales is calculated

---

backend/api/viewsets/model_year_report.py
backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/app/css/ComplianceReport.scss
frontend/src/compliance/AssessmentEditContainer.js
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/components/AssessmentEditPage.js

Changelog:
- Adjustments are now being saved
- Fixed an issue with ComplianceObligation saving unspecifiedCreditBalance saving twice

ZEVA-561: Adjustments Saving

---

backend/api/services/model_year_report.py
backend/api/viewsets/model_year_report.py
frontend/src/compliance/AssessmentContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/ComplianceReportAlert.js

- Used existing submission function to update the status of the report
- added a recommended case for alert
- also updated backend status update for model year report
** not complete yet, will continue working on this.

ZEVA-545: Update status of report from submitted to recommended

---

frontend/src/app/router.js
frontend/src/compliance/ComplianceReportSummaryContainer.js

Changelog:
- Removed the conditions to redirect the user to list page if certain permissions are not available

Enabled summary page for IDIR users

---

backend/api/models/organization.py
backend/api/serializers/model_year_report.py
backend/api/serializers/organization.py
backend/api/viewsets/model_year_report.py
frontend/src/app/utilities/formatNumeric.js
frontend/src/compliance/SupplierInformationContainer.js
frontend/src/compliance/components/SummarySupplierInfo.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js

Changelog:
- Fixed sales not saving
- Fixed calculation of average sales
- Fixed Empty Box
- Rounded values
- Fixed supplier class not reading correctly

ZEVA-606: Fixed Supplier Information Bugs

---

backend/api/serializers/model_year_report_assessment.py
backend/api/viewsets/model_year_report.py
frontend/src/app/css/ComplianceReport.scss
frontend/src/compliance/AssessmentContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js

-updates assessment serializer and details page so that
-a dictionary is passed for in compliance (report and prior year)
-deficit values are passed
-penalty is passed
-decision description and id are passed
-adds functionality for analyst to recommend a report with penalty and radio selections posting to database

Add deficit, starting balance, and ending balance to assessment

---

frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/components/ComplianceObligationAmountsTable.js
frontend/src/compliance/components/ComplianceObligationDetailsPage.js
frontend/src/compliance/components/ComplianceObligationReductionOffsetTable.js
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js

Changelog:
- Red text should only be applied for below 0
- Fixed sorting to ascending
- Added more separation between the tables
- Fixed calculations

ZEVA-609: Compliance Obligation Cleanup

---

backend/api/serializers/model_year_report.py
backend/api/serializers/model_year_report_compliance_obligation.py
backend/api/serializers/model_year_report_vehicle.py
backend/api/viewsets/model_year_report.py
backend/api/viewsets/model_year_report_compliance_obligation.py
backend/api/viewsets/model_year_report_consumer_sales.py
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js
frontend/src/compliance/components/SummarySupplierInfo.js

- created a new param for summary page requests, if param == True, load from the snapshot.
- made bullet points consistent
-  Added message about last time saved and if page is not saved.

ZEVA-610:Summary Bugs

---

backend/api/models/model_year_report.py
backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/app/css/ComplianceReport.scss
frontend/src/app/router.js
frontend/src/app/utilities/calculateCreditAReduction.js
frontend/src/app/utilities/calculateCreditReduction.js
frontend/src/compliance/AssessmentContainer.js
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/ComplianceReportAssessmentContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/AssessmentEditPage.js
frontend/src/compliance/components/ComplianceObligationAmountsTable.js
frontend/src/compliance/components/ComplianceObligationDetailsPage.js
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js

Changelog:
- Assesssment Page should now work more closely to compliance obligation in terms of calculation
- Refactored some code by externalizing some large functions
- Some ESLint Fixes
- Changed to allow decimals

ZEVA-611: Assessment Fixes

---

backend/api/serializers/credit_transaction.py
backend/api/services/credit_transaction.py
frontend/src/app/css/ComplianceReport.scss
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
frontend/src/compliance/components/ComplianceReportsTable.js
frontend/src/compliance/components/ConsumerSalesDetailsPage.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js
frontend/src/credits/components/CreditTransactionListTable.js

- cursor icon on the link from consumer sales 
- fix address labels on the supplier information page
- spell out supplier class in Model Year Reports List 
- credit transfer away add negative symbol
- concatenate modelYear with Transaction Type for credit transaction table

BugFix: added model year to the Transaction column and Monday bugs

---

frontend/src/compliance/ComplianceReportsContainer.js

Changelog:
- Added current year as the default year

ZEVA-612: Added default year for Model year report if no reports existed

---

frontend/src/app/css/ComplianceReport.scss
frontend/src/app/utilities/calculateCreditReduction.js
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/ComplianceReportsContainer.js
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
frontend/src/compliance/components/ComplianceReportsTable.js
frontend/src/compliance/components/ConsumerSalesDetailsPage.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js

Changelog:
- ESLint fixes
- Removed duplicate code between unspecifiedCreditReduction and calculateCreditReduction

ZEVA-612: Minor code cleanup

---

frontend/src/compliance/ComplianceReportsContainer.js
frontend/src/compliance/components/ComplianceObligationReductionOffsetTable.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js

Changelog:
- Added more checks to make sure that it doesn't throw an error if its a new report

Fixed New Report throwing an error

---

backend/api/serializers/credit_agreement.py
backend/api/urls.py
backend/api/viewsets/credit_agreement.py
frontend/src/creditagreements/CreditAgreementsEditContainer.js
frontend/src/creditagreements/components/CreditAgreementsForm.js
frontend/src/credits/components/CreditAgreementsFilter.js
frontend/src/credits/components/CreditAgreementsListPage.js

-adds agreements to urls, adds agreements viewset, save serializer, updates frontend so correct value is passed for organization

agreement create functionality

---

frontend/src/creditagreements/components/CreditAgreementsForm.js

agreement minor changes

---

backend/api/models/organization.py
backend/api/serializers/organization_deficit.py
backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/components/ComplianceObligationAmountsTable.js

Not a direct objective for the card, but this needs to be done first.
Changelog:
- Added existing deficits as part of the calculation

ZEVA-634: Existing Deficits

---

backend/api/viewsets/credit_agreement.py
frontend/src/app/routes/CreditAgreements.js
frontend/src/creditagreements/CreditAgreementsEditContainer.js

Changelog:
- Transaction Types are now fetched from the backend

ZEVA-631: Retrieve Transaction Types from the Backend

---

backend/api/serializers/credit_agreement.py
frontend/src/app/components/Button.js
frontend/src/creditagreements/CreditAgreementsDetailsContainer.js
frontend/src/creditagreements/CreditAgreementsEditContainer.js
frontend/src/creditagreements/components/CreditAgreementsAlert.js
frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js
frontend/src/creditagreements/components/CreditAgreementsForm.js

- Added conditions in display page so that it display information on the page based on the user(supplier or Govt)
- if there is agreement id, get the details from the database which is working for idir user display page.
- if there is no id, such as for bceid user at this point, displaying static value( this will change as there will be ids list for bceId users once the transaction are complete, there is a new card 639 for this  in the backlog )
- made some changes in the serializer to get the details from the DB.( pending: attachment and credits data)
- Made UI changes.

Zeva 635: Initial PR for IDIR Display page

---

backend/api/serializers/credit_agreement.py
frontend/src/creditagreements/CreditAgreementsEditContainer.js

Changelog:
- Adjustments should now be passed and inserted into their respective tables

ZEVA-637: Adjustments are now being added 

---

backend/api/serializers/credit_agreement.py
backend/api/viewsets/credit_agreement.py
frontend/src/app/routes/CreditAgreements.js
frontend/src/creditagreements/CreditAgreementsDetailsContainer.js
frontend/src/creditagreements/CreditAgreementsEditContainer.js
frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js
frontend/src/creditagreements/components/CreditAgreementsDetailsTable.js
frontend/src/creditagreements/components/CreditAgreementsForm.js

- Added attachments and credit content in detail serializer and display it on idir page
- saving idir comment to the database and display it based on user(supplier or govt)

Zeva 635: IDIR display page

---

backend/api/serializers/credit_agreement.py
backend/api/serializers/model_year_report.py
backend/api/viewsets/model_year_report.py
frontend/src/app/utilities/calculateCreditReduction.js
frontend/src/compliance/AssessmentEditContainer.js
frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/components/AssessmentEditPage.js
frontend/src/creditagreements/CreditAgreementsEditContainer.js

Changelog:
- Removed the old adjustments section from the Model Year Report
- Fixed a bug with the credit calculation where it was allowing more credits to be used up for unspecified deductions

ZEVA-637: Removed adjustments from Model Year Report

---

backend/api/models/credit_agreement_statuses.py
backend/api/serializers/credit_agreement.py
backend/api/viewsets/credit_agreement.py
frontend/src/creditagreements/CreditAgreementsDetailsContainer.js
frontend/src/creditagreements/CreditAgreementsEditContainer.js
frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js

-fixes bug with optional agreement id on form
-adds ability to 'delete' agreements
-adds history to serializers
-adds status changes to agreement save (update) serializer

Zeva624 - delete agreements when in draft form

---

backend/api/viewsets/credit_agreement.py

-fixes queryset in credit agreement viewset

credit agreement queryset fix

---

backend/api/serializers/credit_agreement.py
frontend/src/creditagreements/CreditAgreementsDetailsContainer.js
frontend/src/creditagreements/components/CreditAgreementsAlert.js
frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js

-fixes a condition on backend seriaizer
-fixes bug on alert so recommended agreements display
-submit to director now changes status to recommended

zeva 601 - status change

---

backend/api/services/credit_transaction.py

Changelog:
- Added a check when issuing a credits so that it doesnt throw an error if there are no model year reports

Fixed an issue with the issuance of credits

---

frontend/src/creditagreements/CreditAgreementsEditContainer.js

-fixes credit agreement tab so it is active on form opening

bug - credit agreement tab

---

frontend/src/creditagreements/components/CreditAgreementsListPage.js
frontend/src/creditagreements/components/CreditAgreementsListTable.js

Changelog:
- Fixed a bug with the react table
- ESLint Fixes

Fixed listing page

---

frontend/src/app/router.js
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/ComplianceObligationReductionOffsetTable.js
frontend/src/compliance/components/SummaryCreditActivityTable.js
frontend/src/creditagreements/CreditAgreementsDetailsContainer.js
frontend/src/creditagreements/CreditAgreementsEditContainer.js
frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js
frontend/src/creditagreements/components/CreditAgreementsForm.js

Changelog:
- Combined Balance and Deficit together
- Edit functionality for Credit Agreement

Edit function for Credit Agreement. Obligation/Summary front-end fixes

---

backend/api/models/vehicle.py

Changelog:
- Added 1.1 or 1.3 as max value for class B vehicles

ZEVA-643: Updated Class B Vehicles Calculation

---

backend/api/models/vehicle.py
frontend/src/app/css/ComplianceReport.scss
frontend/src/compliance/ComplianceReportsContainer.js
frontend/src/compliance/components/ComplianceReportListPage.js
frontend/src/compliance/components/ComplianceReportSignOff.js
frontend/src/organizations/VehicleSupplierReportListContainer.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js

Changelog:
- Removed dropdown for New Report
- ESLint cleanup
- Added cursor hover for the confirmation labels

ZEVA-644: Model Year Report Updates

---

backend/api/viewsets/credit_agreement.py
backend/api/viewsets/model_year_report.py
frontend/src/app/components/CommentInput.js
frontend/src/app/css/ComplianceReportTabs.scss
frontend/src/compliance/AssessmentContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/ComplianceReportTabs.js
frontend/src/compliance/components/SummarySupplierInfo.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js
frontend/src/creditagreements/CreditAgreementsDetailsContainer.js
frontend/src/credits/components/CreditApplicationHeader.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/dashboard/components/OrganizationDetails.js
frontend/src/dashboard/components/UserSettings.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js

Changelog:
- Fixed assessment save/issue button throwing error at times
- Fixed colours for statuses when assessment is recommended
- Updated director view to show only the selected compliance statement
- Auto redirect when an analyst adds a comment for the director
- Penalty input now disabled until related statement is selected
- Address Optional should now be showing
- Auto redirect for credit agreement delete
- No longer showing deleted credit agreements

Fixes for latest bug report 

---

backend/api/viewsets/model_year_report.py
frontend/src/compliance/AssessmentContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/AssessmentEditPage.js
frontend/src/compliance/components/ComplianceReportsTable.js

Changelog:
- Removed handleSubmit from handleAddBceidComment
- Added call to save for the backend

Fixed an issue with comment not saving. Removed unnecessary condition

---

frontend/src/app/components/CommentInput.js
frontend/src/app/components/ReactTable.js
frontend/src/app/css/Dashboard.scss
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditRequestValidatedDetailsPage.js
frontend/src/credits/components/CreditRequestsPage.js
frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/dashboard/components/Administration.js

Changelog:
- React tables now tabbable
- Disabled tabbing inside react-quill
- Changed button to Link in the Dashboard for IDIR

ZEVA-370: Accessibility Improvements

---

backend/api/serializers/user.py
frontend/src/creditagreements/components/CreditAgreementsAlert.js
frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js
frontend/src/dashboard/DashboardContainer.js
frontend/src/organizations/VehicleSupplierCreditTransactionListContainer.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/organizations/components/OrganizationDetailsPage.js
frontend/src/organizations/components/OrganizationListPage.js
frontend/src/organizations/components/VehicleSupplierUserListPage.js

-fixes error with role.code givign error on user serializer
-lints

bug fix user edit and linting

---

backend/api/serializers/dashboard.py
backend/api/serializers/model_year_report.py
backend/api/services/model_year_report.py
backend/api/viewsets/model_year_report.py
backend/api/viewsets/model_year_report_compliance_obligation.py
backend/api/viewsets/model_year_report_consumer_sales.py
frontend/src/app/css/ComplianceReportTabs.scss
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/SummaryCreditActivityTable.js

Changelog:
- Returned is now showing up as Submitted for BCEID Users
- Fixed transferred away not showing up
- Fixed the dates for the agreements

Report Bug Fixes

---

backend/api/serializers/model_year_report.py
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/ComplianceReportsContainer.js
frontend/src/compliance/components/ComplianceReportListPage.js
frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js
frontend/src/compliance/components/ComplianceReportsTable.js

Changelog:
- Added compliant status to model year report table
- Update how compliant, obligation totals and credit a obligations are calculated

Added compliant, obligation and obligation totals

---

frontend/src/creditagreements/CreditAgreementsEditContainer.js
frontend/src/creditagreements/components/CreditAgreementsFilter.js
frontend/src/creditagreements/components/CreditAgreementsListTable.js
frontend/src/credits/components/CreditTransactionListTable.js
frontend/src/dashboard/DashboardContainer.js

-adds proptypes, fixes code that was getting error messages on transaction list table

more linting

---

backend/api/models/vehicle_statuses.py
backend/api/viewsets/vehicle.py
frontend/src/vehicles/VehicleEditContainer.js
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js

-adds deleted status to vehicle statuses
-adds delete button to vehicle form and details page that are rendered if vehicle is draft
-adds modal logic to form page with delete status
-adds handle status change to edit container

zeva648 - delete draft/changes requested vehicle

---

backend/api/services/model_year_report.py
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/organizations/VehicleSupplierCreditTransactionListContainer.js
frontend/src/organizations/components/VehicleSupplierSalesListPage.js

Changelog:
- Some ESLint fixes
- Moved comments back to previous condition and changed condition

Report bugs cleanup

---

frontend/src/credits/components/CreditTransactionListTable.js

Changelog:
- Added a check so in case the variable is undefined it won't crash the page

Added a check to make sure it never throws errors

---

backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/app/utilities/calculateCreditReduction.js
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js

Changelog:
- Changed logic for starting balance
- Fixed an issue with how obligation is handling deficits

Compliance Obligation Starting Balance

---

frontend/src/app/utilities/getComplianceObligationDetails.js

Changelog:
- Changed the js code so it doesn't throw undefined errors

Compliance Obligation Fix

---

backend/api/serializers/model_year_report_supplemental.py
backend/api/viewsets/model_year_report.py

Changelog:
- Call Supplier information as part of the supplemental report serializer

Added SupplierInformationSerializer into the supplementary report

---

backend/api/serializers/model_year_report_supplemental.py
backend/api/viewsets/model_year_report.py

Changelog:
- Moved the content from ModelYearReportSupplementalSupplierSerializer into ModelYearReportSupplementalSerializer
- Changed ModelYearReportSupplementalSupplierSerializer to retrieve the values for Supplier Information Changes

Assessment Data in Serializer

---

backend/api/viewsets/model_year_report_compliance_obligation.py

-changes condition for retrieving snapshots vs new data

zeva 674 - assessment snapshot bug

---

backend/api/models/model_year_report.py
backend/api/viewsets/model_year_report.py
frontend/src/app/router.js
frontend/src/app/routes/SupplementaryReport.js
frontend/src/compliance/AssessmentContainer.js
frontend/src/supplementary/SupplementaryContainer.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

Changelog:
- Now creates a new record when an IDIR users recommends a supplemental report
- Allow viewing of specific supplemental reports based on ID

ZEVA-685: Create Reassessment Report from Supplemental

---

frontend/src/credits/components/CreditRequestVINListPage.js

Changelog:
- Fixed an issue with the VIN filtering where typing in "11" would cause the results to show as though you only typed in "1"

ZEVA-676: Fix for VIN Filtering issues

---

backend/api/viewsets/model_year_report.py
frontend/src/compliance/components/ComplianceHistory.js
frontend/src/supplementary/SupplementaryContainer.js

Changelog:
- Added refresh details check on the url
- Clicking on the details now refreshes the page correctly

History Links

---

frontend/src/app/css/Supplementary.scss
frontend/src/compliance/components/ComplianceHistory.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

Changelog:
- Reduced some padding

Make the styling more consistent with the rest of the site

---

backend/api/viewsets/model_year_report.py
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/ComplianceHistory.js
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
frontend/src/supplementary/SupplementaryContainer.js
frontend/src/supplementary/components/CreditActivity.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

Changelog:
- Fixed issue with LDV Sales not saving 
- Recommend and other buttons now hidden if feature is disabled
- Fixed an issue with credit activity values being overwritten
- Fixed starting balance not loading when new values were saved

ZEVA-701: Bugfixes

---

backend/api/models/sales_submission_content.py
backend/api/serializers/sales_submission.py
backend/api/services/sales_spreadsheet.py
backend/api/viewsets/credit_request.py
frontend/src/credits/CreditRequestVINListContainer.js

Changelog:
- Fixed issue with download not showing sales date
- Attempted fix for the vague reason provided

ZEVA-695: Fixed an issue with the excel download not showing sales date

---

frontend/src/app/components/Navbar.js
frontend/src/app/utilities/formatNumeric.js
frontend/src/credits/components/CreditBalanceTable.js
frontend/src/credits/components/CreditTransactionListTable.js
frontend/src/organizations/components/OrganizationsTable.js

-adds extra argument and logic to formatnumeric to show brackets instead of minus symbol for negative balances
-adds extra argument in formatNumeric call to spots where balance is listed

ZEVA 698 - negative balances brackets

---

frontend/src/app/utilities/calculateCreditReduction.js

Changelog:
- Changed how the calculation works from removing by year first, to removing by credit type first

ZEVA-706: Changed how the calculation works

---

backend/api/viewsets/model_year_report_compliance_obligation.py

Changelog:
- Changed how we do filtering to_dates and use the next day instead but using lt instead of lte

ZEVA-713: Fixed an issue with the to_date ignoring anything past 00:00:00

---

backend/api/services/model_year_report.py

Changelog:
- Fixed an issue where a credit transaction from the bceid user model year report is being counted together with the changes from the IDIR user

Credit Transaction Fix

---

backend/api/serializers/model_year_report_supplemental.py
frontend/src/compliance/ComplianceReportSummaryContainer.js
frontend/src/compliance/components/SummaryCreditActivityTable.js

Changelog:
- provisionalBalanceAfterCreditReduction is now manually calculated for Summary
- Fixed errors with fetching latest supplemental status

CTHUB-46: Fixed Summary/Compliance Obligation Discrepancy

---

frontend/src/supplementary/SupplementaryContainer.js

-adds redirect to listing page if supplemental draft is deleted

zeva 721 - delete supplementary draft bug

---

frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/credits/components/CreditTransactions.js

Changelog:
- Fixed word wrapping 
- If a row in credit balances is empty, then it will no longer show up

CTHUB-48,49: Fixed word wrapping

---

frontend/src/supplementary/components/ZevSales.js

-fixes column widths in supplementary zev sales table

zeva 720 - sales table column widths

---

backend/api/viewsets/model_year_report.py
frontend/src/compliance/components/ComplianceHistory.js

Changelog:
- Fixed submitted showing up once only and out of order if multiple supplementary reports have been submitted
- Fixed an issue where returned supplementaries are not accessible

Fixed the submitted record in history being out of place

---

backend/api/serializers/model_year_report_supplemental.py
frontend/src/supplementary/SupplementaryContainer.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

-adds exclude to supplemental  queryset to exclude deleted statuses
-adds bceid comment array to details page
-switches what bceid comment input is expecting for default value so comments actually appear

zeva723 - saved comments not appearing

---

frontend/src/app/components/CreditTransactionTabs.js
frontend/src/creditagreements/components/CreditAgreementsListPage.js
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js

-disables submit if vehicle is over weight 
-removes vehicle class and credit class from displaying on details page if over weight

Ctub 44 - zev model weight

---

backend/api/models/model_year_report.py
backend/api/viewsets/model_year_report.py
frontend/src/app/css/Login.scss
frontend/src/compliance/components/ComplianceHistory.js
frontend/src/supplementary/SupplementaryContainer.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

Changelog:
- Deleted other parts of the supplemental report to actually clear it
- Fixed returned status not being recognized as draft

CTHUB-58: Fixed delete issues

---

backend/api/models/model_year_report.py
backend/api/serializers/sales_submission.py
backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/compliance/ComplianceReportSummaryContainer.js

Changelog:
- Default value for icbc_snapshot variable
- Deficit being taken into equation for looking at balance after provisions

CTHUB-63: Fixed missing reductions on summary and Credit Application Validation

---

backend/api/models/supplemental_report.py
backend/api/serializers/model_year_report_noa.py
backend/api/viewsets/model_year_report.py
backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/package-lock.json
frontend/package.json
frontend/src/app/css/Accordion.scss
frontend/src/app/routes/Compliance.js
frontend/src/compliance/AssessmentContainer.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/ComplianceHistory.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

Changelog:
- New design for the history
- Backend controls for most of how the content is delivered

CTHUB-54: Updated Compliance History

---

backend/api/serializers/model_year_report_noa.py
backend/api/viewsets/model_year_report.py
frontend/src/compliance/components/ComplianceHistory.js

Changelog:
- Only one save or submitted shows up now
- Only one recommended shows up now

CTHUB-100: Cleaned Up Supplemental Report History

---

backend/api/serializers/model_year_report_supplemental.py
frontend/src/app/css/Supplementary.scss
frontend/src/supplementary/SupplementaryContainer.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

Changelog:
- Fixed some status issues
- Allows you to switch between the supplementary submission and reassessment report

CTHUB-101: Tabs for Supplementary and Reassessment

---

frontend/src/organizations/components/VehicleSupplierDetailsPage.js

REmoved hasSubmittedReport condition from add and delete button.

CTHUB-97: ZEVA - Allow IDIR user to edit MY2017-2019 sales figures

---

backend/api/services/icbc_upload.py

Changelog:
- Now updates the data if VIN is the same as one that already exists

CTHUB-99: Override existing data when same icbc data is being uploaded

---

backend/api/services/icbc_upload.py
backend/api/viewsets/icbc_verification.py

Changelog:
- Header Names are now adjusted to be uppercase (internally)
- Changed how the csv is being read

ICBC Upload Fix

---

backend/api/services/icbc_upload.py
backend/api/viewsets/icbc_verification.py

Changelog:
- Added back the code to keep the connection alive

Fix upload icbc performance

---

backend/api/serializers/model_year_report_supplemental.py
backend/api/viewsets/model_year_report.py
frontend/src/app/css/Supplementary.scss
frontend/src/compliance/components/ComplianceObligationReductionOffsetTable.js
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
frontend/src/supplementary/SupplementaryContainer.js
frontend/src/supplementary/components/CreditActivity.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js
frontend/src/supplementary/components/SupplierInformation.js
frontend/src/supplementary/components/ZevSales.js

Changelog:
- Fixed colours for the supplementary tabs
- Fixed highlighting
- Fixed negative values not showing
- Fixed records not populating

Fixed various bugs

---

backend/api/serializers/model_year_report.py
backend/api/serializers/model_year_report_noa.py
backend/api/serializers/model_year_report_supplemental.py
backend/api/viewsets/model_year_report_consumer_sales.py
frontend/src/app/css/Supplementary.scss
frontend/src/compliance/components/ConsumerSalesDetailsPage.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

Changelog:
- History for submitted by government user is no longer included in the history as it's causing issues

Fixed issue where submitted gets overridden by government user

---

frontend/src/compliance/components/ComplianceHistory.js
frontend/src/supplementary/SupplementaryContainer.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

Changelog:
- Removed the conflict marker
- Fixed duplicate reassessment declaration

Fixed an issue where there's a merge conflict marker

---

backend/api/models/sales_submission_content.py
frontend/src/app/css/Suppliers.scss
frontend/src/compliance/components/ComplianceHistory.js
frontend/src/compliance/components/ComplianceReportAlert.js
frontend/src/creditagreements/components/CreditAgreementsAlert.js
frontend/src/organizations/VehicleSupplierDetailsContainer.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js

Changelog:
- Changed the Director to Government of B.C.
- Fixed an issue where rejected vins are still considered in the system
- Added Edit button for LDV Sales

CTHUB-117: Re-validate Fix

---

frontend/src/app/components/CommentInput.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js

Changelog:
- Added additional check for government users before showing the comment input box and recommendation options

Fixed an issue where IDIR elements are still showing up for BCEID users

---

backend/api/serializers/model_year_report.py
backend/api/serializers/model_year_report_supplemental.py
backend/api/viewsets/model_year_report.py
backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/supplementary/SupplementaryContainer.js
frontend/src/supplementary/components/CreditActivity.js
frontend/src/supplementary/components/SupplementaryDetailsPage.js
frontend/src/supplementary/components/SupplierInformation.js
frontend/src/supplementary/components/ZevSales.js

Changelog:
- Fixed highlighting
- Fixed duplicate text
- Fixed director workflow

Fixed various issues with supplementary report

---

backend/api/services/model_year_report.py

-modifies how reductions are inserted into transaction table (given date of sept 30 of the model year report year + 1)
-modifies how account balance is changed after model year report issued, changes associated with reductions are given effective dates of sept 30 of the model year report year + 1

CTHUB 166 - SECOND HALF -  transaction changes

---

docker-compose.yml
frontend/Dockerfile

some mods to get docker running locally for me.

mod the npm install

---

backend/api/services/sales_spreadsheet.py
backend/api/viewsets/credit_request.py
frontend/src/app/routes/CreditRequests.js
frontend/src/credits/components/AnalystRecommendationHeader.js
frontend/src/credits/components/CreditRequestDetailsPage.js
frontend/src/credits/components/CreditRequestValidatedDetailsPage.js
frontend/src/credits/components/DownloadAllSubmissionContentButton.js

-adds link to view application details for analyst
-adds functions, buttons to allow applicaton information to be downloaded to excel

zeva 307 - download details

---

README.md
backend/api/services/sales_spreadsheet.py
frontend/src/credits/components/VINListTable.js

-updates readme
-moves validated boolean into for loop, uses record of sale status instead of submission status
-fixes bug on vin list table, now shows snapshot data rather than current data if it exists
-linting

zeva 369 - display snapshot data on sales table

---

backend/api/viewsets/model_year_report_compliance_obligation.py

-adds filter for from_gov in details for retrieving modelYearReportComplianceObligation objects

ZEVA401 - Credit balance being doubled in MY21 model year reports

---

backend/api/models/sales_submission_content.py
backend/api/viewsets/credit_request.py
frontend/src/credits/CreditRequestVINListContainer.js
frontend/src/credits/components/CreditRequestVINListPage.js
frontend/src/credits/components/VINListTable.js
frontend/src/vehicles/components/VehicleForm.js

- icbc_verification query optimized
- page size fix on vinlist
- rejected records filter added to credit request
- timeout refresh on filter input added

Fix: VinList and Credit Request Optimizations - ZEVA-424

---

developer-guide.md
frontend/src/credits/components/CreditTransactions.js

-adds some extra instructions to the developer guide
-removes filter from balances when passing to creditBalanceTable as items prop

fix: zeva 431 - Detailed Credit Balance bug

---

frontend/src/vehicles/components/VehicleForm.js

fix: moves spaces function above where it is called

fix: zeva 453 - add new vehicle form errors

---

frontend/src/app/css/App.scss

fix: zeva 454 - comment boxes overlapping

---

frontend/src/app/utilities/formatNumeric.js

fix: adds decimals to negative values in round brackets

fix: ZEVA 452 - transaction page negative balances decimals

---

frontend/src/compliance/components/ComplianceObligationDetailsPage.js
frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js
frontend/src/compliance/components/ConsumerSalesDetailsPage.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js

adds condition for displaying checkboxes and button bars on model year report pages

feat: ZEVA 449 - Hide button bar on MY report after submit

---

frontend/src/creditagreements/components/CreditAgreementsListTable.js

-changes some column names
-re-orders, changes some alignments
-adds function to use minus symbol with negative numbers for credits
-adds getProps to credits column for styling negative values with red text

feat: zeva-461- Updates to credit agreements page 

---

frontend/src/app/components/SessionTimeout.js
frontend/src/app/router.js

https://apps.nrs.gov.bc.ca/int/jira/browse/ZELDA-418

get timeout from keycloak

---

frontend/src/app/components/SessionTimeout.js

https://apps.nrs.gov.bc.ca/int/jira/browse/ZELDA-418

logout on idle timeout

---

.github/ISSUE_TEMPLATE/bug.md

Updating an issue template so that we can see it in Zenhub

Update issue templates - Bug

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/spike.md
.github/ISSUE_TEMPLATE/task-.md
.github/ISSUE_TEMPLATE/user-story-.md

These templates are for Zeva tickets

Update issue templates

---

.gitignore
frontend/src/app/components/CommentInput.js
frontend/src/app/components/__tests__/Alert.test.js
frontend/src/app/components/__tests__/Button.test.js
frontend/src/app/components/__tests__/Comment.test.js
frontend/src/app/components/__tests__/CommentInput.test.js
frontend/src/app/components/__tests__/ComplianceTabs.test.js
frontend/src/app/components/__tests__/CreditTransactionTabs.test.js
frontend/src/app/components/__tests__/DetailField.test.js

Added front-end tests for Alert, Button, Comment and CommentInput components.  Also updated the CommentInput component to add id's to make testing it easier.

Front-End Unit Testing

---

backend/api/viewsets/model_year_report.py
developer-guide.md

fixes issue by adding 'DRAFT' status to viewset condition where it updates SupplementaryAssessment table

fix: ZEVA 1340 - Reassessment radio button selection fails to save on first try

---

frontend/src/supplementary/SupplementaryContainer.js

Looking at my original approach to zeva 1354, I wasn't too happy with it; I think this is better as the same information doesn't live in two states now.

fix: zeva-1354 - a different solution

---

frontend/src/supplementary/components/SupplementaryAnalystDetails.js

fix: removes newLdvSales from supplementaryAnalystDetails

fix: bugfixes

---

backend/api/services/model_year_report.py
backend/api/services/send_email.py
backend/api/viewsets/model_year_report.py

Edited logic for emails to be sent when a reassessment is issued, approved or returned.

More Fixes for Email Notifications - 1265

---

backend/api/viewsets/vehicle.py

Added vehicle's organization id and update user to ZEV Model state change requests so emails can send properly.

ZEV Model Validation Email Notification Fix

---

frontend/src/supplementary/components/SupplementaryAnalystDetails.js

-adds upload component to analyst page if report is editable

Zeva fix - adds upload component to analyst page

---

backend/api/models/model_year_report.py
backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
frontend/src/supplementary/components/CreditActivity.js

Added logic for new model year reports to pull closing balance from a reassessment if there is one

Reassessment Balances Fix - 1259

---

frontend/src/supplementary/components/CreditActivity.js
frontend/src/supplementary/components/SupplementarySupplierDetails.js
frontend/src/supplementary/components/__tests__/SupplementarySupplierDetails.test.js

Also includes some fixes/changes for issues that came up when writing/running the unit tests

feat: SupplementarySupplierDetails unit tests

---

frontend/src/compliance/AssessmentContainer.js

fix: ZEVA 1490 - text change

---

frontend/src/supplementary/components/SupplementaryAnalystDetails.js
frontend/src/supplementary/components/SupplementaryDirectorDetails.js

attachments visible for director and analyst with any status

fix: ZEVA 1490 - attachments

---

backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/supplementary/components/SupplementaryCreate.js

Bug fixes for ldv sales, compliance obligation numbers and text changes throughout the reassessment process.

Reassessment Bug Fixes

---

frontend/src/compliance/components/ComplianceHistory.js

Revert "fix: Zeva 1490 history component bugs and changes"

---

backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/src/supplementary/components/SupplementaryCreate.js

Revert "Reassessment Bug Fixes"

---

backend/api/services/send_email.py

- Reassigned body variable to save email text changes.

Email Description Bug Fix

---

frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/supplementary/components/SupplementaryAnalystDetails.js
openshift/scripts/import-data.sh

- Added logic to check if a supplemental report exists before showing "Return to Vehicle Supplier" button
- Small script update to point to new existing test database pod

Return to Vehicle Supplier Fix

---

frontend/src/compliance/components/ComplianceHistory.js
frontend/src/supplementary/SupplementaryContainer.js

- Created logic to display the original user who made a status change.
- Small text update for clarity.

Model Year Reporting History Bug Fix

---

frontend/.eslintrc.js
frontend/__mocks__/axios.js
frontend/jest.setup.js
frontend/notifications.js
frontend/src/app/__tests__/router.test.js
frontend/src/app/components/__tests__/ComplianceTabs.test.js
frontend/src/app/components/__tests__/CreditTransactionTabs.test.js
frontend/src/app/components/__tests__/Disclaimer.test.js
frontend/src/credits/components/__tests__/CreditTransactionListTable.test.js
frontend/src/credits/components/__tests__/CreditTransfersDetailsPage.test.js
frontend/src/supplementary/components/CreditActivity.js
frontend/src/supplementary/components/SupplementaryAnalystDetails.js
frontend/src/supplementary/components/SupplementaryCreate.js
frontend/src/supplementary/components/SupplementaryDirectorDetails.js
frontend/src/supplementary/components/SupplementarySupplierDetails.js
frontend/src/supplementary/components/UploadEvidence.js
frontend/start.js

- Moved comment box for director from recommendation to reassessment page
- Removed supplier comment box for gov users
- Small text changes for clarity
Note: Linting done to /web directory.

Comment Box Updates

---

frontend/src/compliance/components/ComplianceHistory.js
frontend/src/supplementary/SupplementaryContainer.js

This reverts commit 169698bc135d856434ab4fb86882758957c85b95.

Revert "Model Year Reporting History Bug Fix (#1593)"

---

openshift/scripts/import-data.sh

fix: updates import script with spilo pod for prod

fix: import script update (no zenhub ticket)

---

frontend/src/compliance/components/ComplianceHistory.js
frontend/src/supplementary/SupplementaryContainer.js

- Reverted logic for not allowing directors to save a report.
- Modified logic to trim history information passed to the frontend
- Small text change for clarity

Fix: Report History Overwriting - 1640

---

backend/api/services/send_email.py

- Added logic to handle different data structure for users in the request.
- Modified lists inside test_info object so they can properly save/iterate

Fix: Test Email Notifications - 1633

---

backend/api/serializers/model_year_report.py
backend/api/services/model_year_report.py
backend/api/viewsets/model_year_report.py

feat: adds beginning of service for adjusting credits based on reassessment, LDV sales from reassessments are now being written to the organizationLdvSales table and are displayed on the organization page and should be pulled into future model year reports

feat: ldv sales from reassessments - 1636

---

frontend/src/supplementary/SupplementaryContainer.js
frontend/src/supplementary/components/CreditActivity.js

- Modified logic to pass the entire list of balances instead of just the current year.
- Updated the front end to loop and handle the new list for saving to the database.

Fix: Reassessment Prior Year Credit Balances - 1638

---

frontend/src/compliance/components/SummarySupplierInfo.js

- Added logic to properly display address records on the model year report summary page.

Fix - Summary Tab Address Bug #1781

---

frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js

- Added check for reassessment/supplemental report to display text properly

Fix - Compliance Obligation Credit Text #1713

---

frontend/src/app/components/StatusInterceptor.js
frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/organizations/__tests__/OrganizationDetailsContainer.test.js

fix: added check to exclude gov users from signoff history on credit transfers

Fix: Credit Transfer Signoff User

---

frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js

- Added modal for confirming primary actions on credit agreements.

Task - Credit Agreement Modal Confirmation #1788

---

frontend/src/app/components/StatusInterceptor.js
frontend/src/credits/components/CreditTransfersDetailsPage.js
frontend/src/organizations/__tests__/OrganizationDetailsContainer.test.js

added check to exclude gov users from sign-off history on credit transfers

fix: Credit Transfers Signoff Text Issue

---

frontend/src/app/components/ReactTable.js
frontend/src/compliance/components/ComplianceReportsTable.js
frontend/src/creditagreements/components/CreditAgreementsListTable.js
frontend/src/credits/components/CreditTransfersListTable.js
frontend/src/organizations/components/UsersTable.js
frontend/src/vehicles/components/VehicleListTable.js

- Added front end pagination to all react tabes that require it.

Feat: Index Tables Pagination #1453

---

frontend/src/compliance/components/ComplianceHistory.js

- Only allow the history component to capture 1 history entry per loop of it's data

Fix - Report History Bugs #1863

---

frontend/src/compliance/components/ComplianceObligationDetailsPage.js
frontend/src/compliance/components/ComplianceObligationReductionOffsetTable.js

- Removed unnecessary checkboxes/text for small suppliers regarding credit reductions as they never have any
- Added new text for small suppliers explaining they have no credit reduction or compliance obligation

Task - Small Supplier MYR New Text #1872

---

.github/workflows/create-release.yaml
.github/workflows/dev-build.yaml
.github/workflows/release-build.yaml
backend/api/services/sales_submission.py
charts/zeva-spilo/values-prod.yaml
frontend/package.json

Release Notes:
fix: incorrect 21 warnings

Tracking pull request to merge release-1.52.0 to master

---

backend/api/serializers/credit_agreement.py
frontend/src/creditagreements/CreditAgreementsDetailsContainer.js
frontend/src/creditagreements/components/CreditAgreementsAlert.js
frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js

- Updated serializer to include update user
- Front end user displayed now uses the update user for correct history

Fix: Initiative Agreement Different User Shown For Same Action #1963

---

frontend/src/supplementary/components/CreditActivity.js

- Added formatting function across other places ldv sales are mentioned to keep formatting in sync

Fix - LDV Sales Missing Comma #1939

---

frontend/src/compliance/components/ComplianceObligationAmountsTable.js

Fix: Missing comma on LDV sales #1939

---

frontend/src/dashboard/components/ActionsBceid.js

- Fixing incorrect dashboard link for BCEID users

Fix: Incorrect BCEID dashboard link #1357

---

frontend/src/app/utilities/getClassAReduction.js
frontend/src/app/utilities/getUnspecifiedClassReduction.js
frontend/src/compliance/components/AssessmentEditPage.js
frontend/src/compliance/components/ConsumerLDVSales.js

- Adding logic to remove credit reductions for small suppliers

Fix: Small Suppliers No Credit Reduction #1894

---

frontend/src/compliance/components/ComplianceObligationAmountsTable.js
frontend/src/supplementary/components/CreditActivity.js

- Adding comma to input fields as well

Fix: More Missing Comma Stuff #1939

---

frontend/src/dashboard/components/ActionsBceid.js

- Changed link to different list page

Fix: Fixing Broken Dashboard Link #1357

---

frontend/src/compliance/AssessmentContainer.js
openshift/scripts/ICBCDataProcessor.py
openshift/scripts/run-test-script.sh
openshift/scripts/vinCreator.py

- Added python script to generate excels/csv's with fake VIN's for testing purposes
- Upload test data script updated
- ICBC Data processing app spike code
*Moved to 1.53.0*

Task: Scripts and Test Data #1654

---

frontend/src/compliance/components/ComplianceObligationAmountsTable.js

- Added logic to check for the input field being disabled if true the type it expects become a string and the value passed becomes a formatted number string instead of a number

Fix: Final Missing Comma #1939

---

frontend/src/vehicles/VehicleListContainer.js

- Modifying the filtering on the ZEV models list page to default to only active models

Feat: Active ZEV Models Default Filter #1356

---

frontend/src/vehicles/components/VehicleDetailsPage.js

- Added delete button to the rejected ZEV model page so it can be deleted

Feat: Delete Button For Rejected ZEV Models #1285

---

frontend/src/compliance/components/ComplianceObligationDetailsPage.js
frontend/src/compliance/components/ComplianceReportSummaryDetailsPage.js
frontend/src/compliance/components/ConsumerSalesDetailsPage.js
frontend/src/compliance/components/CreateReassessmentHeader.js
frontend/src/compliance/components/SupplierInformationDetailsPage.js
frontend/src/supplementary/components/SupplementaryCreate.js

fix: removes print button from the actual printed page

fix: zeva 1941 Emily - print button

---

developer-guide.md
openshift/scripts/import-data.sh

updates developer guide and import script for some changes to reflect change to crunchy  and dev instead of test, and note about fixing local database lock

chore: emily- updates developer guide and import script -no zenhub ticket

---

frontend/src/credits/components/CreditRequestAlert.js

fix: adds submission message that gets added to the history for recommended and validated history

fix: Emily - zeva 1964 - submission date

---

backend/api/models/model_year_report.py
backend/api/serializers/model_year_report.py
backend/api/serializers/model_year_report_assessment.py
backend/api/viewsets/model_year_report.py

- Added logic to not display assessment comments, radio button selections or penalty amounts when a report is returned

Fix: Report Returned Fixes #1276

---

frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js

fix: moves conditional statement for comments to the div so the line doesn't appear if there isn't a comment

fix: zeva 2048 - credit agreement comments from director

---

backend/api/viewsets/model_year_report.py

- Added logic to remove assessment comment when a report is resubmitted but maintain comments between the analyst and director

Fix: Report Returned To Supplier #1276

---

backend/api/viewsets/model_year_report.py

- Adding logic to set the assessment display to true when it is submitted/saved

Feat: Recommended Assessment Message #2062

---

frontend/src/creditagreements/components/CreditAgreementsDetailsPage.js

- Allowing comments to appear if a credit agreement is issued without the option to add more comments

Feat: Credit Agreement Internal Commenting #2063

---

frontend/src/compliance/components/ComplianceHistory.js

feat: adds more information to history items with returned status, so idir users can tell who the report was returned by

Feat: zeva 2061: MY report history wording refinement

---

backend/api/services/sales_spreadsheet.py

- Added logic to capture VINs not issued credits when they are manually unselected by an analyst for the error download.

Feat: Credit Application Error Download #2084

---

backend/api/services/bceid_email_spreadsheet.py
backend/api/viewsets/user.py
frontend/src/app/routes/Users.js
frontend/src/users/components/ActiveUsersListPage.js

- Added functionality to download email list with organizations attached for filtering
- Created backend functionality to create an excel spreadsheet
- Created api endpoint to call build excel spreadsheet

Feat: Active Supplier Email Excel Download #2090

---

backend/api/services/bceid_email_spreadsheet.py

- Removing lock on generated excel sheet to allow for sorting/filtering

Fix: Active Emails Spreadsheet #2090

---

frontend/src/compliance/AssessmentContainer.js

fix: adds loading to handle submit

fix: 2113 - load icon

---

backend/api/tests/test_credit_transfers.py

- Updating test to use the on_commit function so that testing happens after all database actions have completed

Task: Amend Test_Transfer_Pass #2045

---

backend/api/tests/test_credit_transfers.py

- Updating test to use on_commit to only test after all database actions have completed

Task: Amend Test_List_Transfer #2057

---

frontend/src/credits/components/CreditRequestDetailsPage.js

- Updated back button routing to return user to the vehicle suppliers credit transactions list or all supplier transactions list based on href state

Fix: Credit Application Back Button Rebase #1983

---

frontend/src/dashboard/components/__tests__/DashboardContainer.test.js

- Tests for Dashboard Container

Task: Add Unit Tests for Dashboard Container #1740

---

frontend/src/compliance/components/ComplianceObligationAmountsTable.js
frontend/src/compliance/components/ConsumerLDVSales.js
frontend/src/compliance/components/SummaryCreditActivityTable.js
frontend/src/supplementary/components/CreditActivity.js

- Updating terminology to reflect new policies

Task: Update Reporting Terminology #2205

---

frontend/src/app/components/TextInput.js
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js

- Adding frontend flagging system for class 2B vehicles

Task: Update ZEVA System for Class 2B Vehicles #2203

---

frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
frontend/src/supplementary/components/CreditActivity.js

- Allowing all credit fields to be modified in reassessments
- Added checks for empty values to avoid errors

Task: Reassessment Credit Modifications #2195

---

frontend/src/salesforecast/components/RecordsUpload.js

- Frontend validation for uploaded spreadsheet records

Task: Frontend Spreadsheet Record Validation #2220

---

developer-guide.md

chore: updates login instructions (removes references to creation_request table)

chore: zeva - update developer guide

---

frontend/src/app/components/TextInput.js
frontend/src/compliance/components/ComplianceObligationAmountsTable.js
frontend/src/compliance/components/ConsumerLDVSales.js
frontend/src/compliance/components/SummaryCreditActivityTable.js
frontend/src/supplementary/components/CreditActivity.js
frontend/src/vehicles/components/VehicleDetailsPage.js
frontend/src/vehicles/components/VehicleForm.js

- Conditionally render text for the vehicle class if it is an idir user. 
- Removes 2B flag for everyone.
- Conditional rendering for vehicles supplied text depending on model year.

Task: Conditionally Render Vehicle Weight Class Text #2223

---

backend/api/serializers/user.py

fix - adds is_government to basic user serializer

fix - idir comments change signature name on credit transfers

---

backend/api/services/credit_transaction.py
backend/api/tests/test_credit_transactions.py
backend/api/tests/test_credit_transfers.py
backend/api/tests/test_utils.py

feat- removes code that automatically reduces transaction credits if deficit exists

ZEVA feat 2284 - reduction

---

frontend/src/vehicles/components/VehicleDetailsPage.js

- Showing correct vehicle class based on weight
- Allowing new max weight

Vehicle Weight Class Fix

---

backend/api/serializers/user.py
backend/api/tests/test_organizations.py
backend/api/tests/test_users.py
backend/api/viewsets/organization.py
backend/api/viewsets/user.py
frontend/src/app/router.js

Tests for User and Organization

2313 Endpoint testing

---

frontend/src/app/utilities/convertToBig.js

fix: convert carry over deficits function

fix: Big error when loading assessment page for org in deficit

---

frontend/src/compliance/ComplianceObligationContainer.js
frontend/src/compliance/__tests__/ComplianceObligationContainer.test.js

Created unit-tests for ComplianceObligationContainer.js, including tests for compliance reduction and credit balance calculations.
The code of ComplianceObligationContainer.js is slightly modified for an edge case.

2292 unit-tests: Compliance Obligation Container

---

frontend/src/app/css/Suppliers.scss
frontend/src/organizations/components/VehicleSupplierDetailsPage.js

-Add a table displaying “Previous Years Vehicle Sales”  (adds separation between sales/suppled on vehicle supplier information page)
-tool tip
-see more/see less

feat: zeva 2366 - Update Supplier Information Table (IDIR User)

---

frontend/src/compliance/__tests__/ComplianceCalculatorContainer.test.js
frontend/src/compliance/__tests__/ComplianceObligationContainer.test.js
frontend/src/compliance/__tests__/ComplianceRatiosContainer.test.js
frontend/src/compliance/components/__testHelpers/CommonTestDataFunctions.js
frontend/src/compliance/components/__tests__/ComplianceObligationAmountsTable.test.js
frontend/src/compliance/components/__tests__/ComplianceObligationDetailsPage.test.js
frontend/src/compliance/components/__tests__/ComplianceRatiosDetailsPage.test.js
frontend/src/compliance/components/__tests__/ComplianceReportAlert.test.js

Tests for #1732:
- Compliance-Obligation-Container
- Compliance-Ratio-Container
- Compliance-Calculator-Container
Tests for #1734:
- Compliance-Obligation-Details-Page
- Compliance-Obligation-Amount-Table
- Compliance-Report-Alert
- Compliance-Ratios-Detail-Page

1732, 1734 - Unit-tests for Compliance and Compliance/components

---

frontend/src/app/components/FileDrop.js
frontend/src/app/components/FileDropArea.js
frontend/src/app/css/App.scss
frontend/src/app/css/FileUpload.scss
frontend/src/salesforecast/components/RecordsUpload.js

- add disabled styling when a file is already uploaded
- update colours 
- add modal for confirmation of removal of file
- update success message

ZEVA-2290: Forecast upload notification improvement

---

developer-guide.md
openshift/scripts/import-data-from-local.sh

adds script, instructions for running new scripts to 1. insert data and 2. update users with keycloak logins

task: import data from local script, readme updated 

---

frontend/src/creditagreements/components/CreditAgreementsForm.js
frontend/src/creditagreements/components/__tests__/CreditAgreementsAlert.test.js
frontend/src/creditagreements/components/__tests__/CreditAgreementsForm.test.js
frontend/src/creditagreements/components/__tests__/CreditAgreementsListPage.test.js

ZEVA-1736: Unit tests for credit agreement components

---

backend/api/tests/test_model_year_reports.py

More tests for model year report endpoint.

ZEVA-2345: Model Year Report Tests

---

backend/api/tests/test_icbc_verification.py

More unit tests for backend, took me a bit to get the mocks right... but starting to get a good grasp of the endpoints!

ZEVA-2348: ICBC Verification ViewSet tests

---

backend/api/tests/test_compliance_obligation.py

Tests for Compliance Obligation

ZEVA-2344: Tests for compliance obligation

---

frontend/src/compliance/ConsumerSalesContainer.js

Task: Update Disabled Save Button Tooltip Text #2434

---

frontend/src/vehicles/components/VehicleDetailsPage.js

Task: Update Vehicle Details Checkbox Text #2433

---

backend/api/services/send_email.py
charts/zeva-apps/charts/zeva-frontend/templates/configmaps.yaml

openshift secrets have been updated as well, by @kuanfandevops

task - 2443 : updates do no reply email

---

README.md
developer-guide.md
frontend/src/app/components/Tooltip.js
frontend/src/compliance/components/ComplianceObligationAmountsTable.js
frontend/src/credits/components/CreditRequestListTable.js
frontend/src/credits/components/CreditRequestSummaryTable.js
frontend/src/credits/components/getAnalystRecommendationColumns.js
frontend/src/dashboard/components/UserSettings.js
frontend/src/organizations/components/VehicleSupplierDetailsPage.js
frontend/src/users/components/UserDetailsForm.js

_Leaving on draft as I confirm that the tooltips have all been covered throughout app - but code / logic should remain virtually unchanged_
- Update tooltips to match mockup
- Use new tooltip through application where applicable
- Update docs to use the new `docker compose` as `docker-compose` is now deprecated (let me know if this is ok)

ZEVA-2444: Update tooltip consistency 

---

backend/api/tests/test_model_year_reports.py

A couple more unit tests for the model_year_reports viewset

ZEVA-2346: More unit tests for model_year_reports

---

backend/api/services/send_email.py

task: edits to email to remove undisclosed

task: removes 'undisclosed recipients' from email

---

backend/api/viewsets/credit_request.py
frontend/src/credits/components/VINListTable.js

- Adding annotated validated field to sort on for vins

Task: Credit Application Validated Sorting Functionality #2436

---

frontend/src/app/css/Footer.scss

Footer will now always be at the bottom of the screen regardless of screen size.

Footer fix

---

frontend/package.json
frontend/src/app/app.js

SSO team upgraded the Keycloak server; we need to make a corresponding upgrade to our frontend keycloak adapter.

update keycloak adapter

---

frontend/src/app/components/Button.js
frontend/src/app/components/CommentInput.js
frontend/src/compliance/components/AssessmentEditableCommentInput.js
frontend/src/compliance/components/ComplianceReportSignOff.js
frontend/src/credits/components/CreditTransfersForm.js
frontend/src/credits/components/CreditTransfersSignOff.js
frontend/src/notifications/components/NotificationListPage.js
frontend/src/organizations/components/OrganizationListPage.js
frontend/src/supplementary/components/SupplementaryAnalystDetails.js
frontend/src/supplementary/components/SupplementaryDirectorDetails.js
frontend/src/supplementary/components/SupplementarySupplierDetails.js
frontend/src/supplementary/components/SupplementaryTab.js

Remove instances of isolated ReactTooltip and replace it with our Tooltip component.

ZEVA-2478: Tooltip refactor

---

frontend/src/app/components/Button.js
frontend/src/app/components/CommentInput.js
frontend/src/compliance/components/AssessmentEditableCommentInput.js
frontend/src/compliance/components/ComplianceReportSignOff.js
frontend/src/credits/components/CreditTransfersForm.js
frontend/src/credits/components/CreditTransfersSignOff.js
frontend/src/notifications/components/NotificationListPage.js
frontend/src/organizations/components/OrganizationListPage.js
frontend/src/supplementary/components/SupplementaryAnalystDetails.js
frontend/src/supplementary/components/SupplementaryDirectorDetails.js
frontend/src/supplementary/components/SupplementarySupplierDetails.js
frontend/src/supplementary/components/SupplementaryTab.js

This reverts commit 9cdfedeed75c7b06686e6b521eaf5b118052a593.

Revert "ZEVA-2478: Tooltip refactor (#2487)"

---

frontend/src/app/components/Button.js
frontend/src/app/components/CommentInput.js
frontend/src/app/components/Tooltip.js
frontend/src/compliance/components/AssessmentDetailsPage.js
frontend/src/compliance/components/AssessmentEditableCommentInput.js
frontend/src/compliance/components/ComplianceReportSignOff.js
frontend/src/credits/components/CreditRequestListTable.js
frontend/src/credits/components/CreditTransfersForm.js
frontend/src/credits/components/CreditTransfersSignOff.js
frontend/src/credits/components/getAnalystRecommendationColumns.js
frontend/src/notifications/components/NotificationListPage.js
frontend/src/organizations/components/OrganizationListPage.js
frontend/src/supplementary/components/SupplementaryAnalystDetails.js
frontend/src/supplementary/components/SupplementaryDirectorDetails.js
frontend/src/supplementary/components/SupplementarySupplierDetails.js
frontend/src/supplementary/components/SupplementaryTab.js

Tooltips added by jonny
Bug fixes by Emily

zeva 2478 - Update tooltips + bug fixes

---

frontend/src/app/css/Credits.scss
frontend/src/credits/CreditTransfersEditContainer.js
frontend/src/credits/components/CreditTransfersSignOff.js

2506-Bug fix: Credit Transfer Buttons Disabling

---

backend/api/viewsets/model_year_report_compliance_obligation.py

- updated business logic on previously existing reports to not double include deficits

Fix: Exclude deficits on previously existing starting balances

---

backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/Dockerfile-Openshift

- Updated business logic on previously existing reports to not double include deficits
- Bitnami is deprecating their images so we have replaced the nginx image being used for a non-root docker.io image

Fix: Nginx Bitnami Image Deprecation Switch

---

backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/Dockerfile-Openshift

- revert to bitnami nginx image but with latest tag

Fix: Bitnami latest tag

---

backend/api/viewsets/model_year_report_compliance_obligation.py
frontend/Dockerfile-Openshift
frontend/nginx.conf

- updated nginx config to move away from bitnami

Fix: Nginx Open Version
